# Evaluation Loop

Runs every active model on every active feature track, target, horizon and pseudo-out-of-sample fold, then saves per-run metrics, predictions and runtimes to `results/raw/<model>/<track>.parquet`.

This notebook only holds configuration. The logic lives in `src/`:

- `src/evaluation/` — folds, track preparation, metrics, the loop itself
- `src/models/` — model functions and `MODEL_REGISTRY`
- `src/features/quantum/` — quantum / classical reservoir feature generators (precomputed into tracks by `scripts/build_quantum_tracks.py`)

To add a model, see the docstring in `src/models/__init__.py`. To add a track, add an entry to `TRACK_CONFIG` below.

## 1. Environment setup

In [1]:
import os
import sys
from pathlib import Path

COLAB = False  # set to True when running in Google Colab

if COLAB:
    REPO_URL  = "https://github.com/manuelarceaguirre/capstone-quantum.git"
    BRANCH    = "clean"
    REPO_ROOT = Path("/content/capstone-quantum")

    %cd /content
    !rm -rf capstone-quantum
    !git clone -b {BRANCH} {REPO_URL}
    %cd /content/capstone-quantum
    !pip install -q pmdarima
    sys.path.insert(0, str(REPO_ROOT))
else:
    # local: walk up from the working directory to the repo root;
    # src/ is importable via `pip install -e .` (see environment.yml)
    REPO_ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "pyproject.toml").exists())

print("Repo root:", REPO_ROOT)

Repo root: C:\dev\projects\capstone-quantum

In [2]:
import warnings

import pandas as pd

from src.evaluation import (
    disaggregate_by_usrec,
    explode_predictions,
    generate_folds,
    load_results,
    load_tracks,
    run_evaluation,
    shared_track,
    summarize,
    write_csv,
)
from src.models import MODEL_REGISTRY

warnings.filterwarnings("ignore")

## 2. Configuration

In [3]:
# --- Paths ---
DATA_DIR    = REPO_ROOT / "data" / "processed"
RESULTS_DIR = REPO_ROOT / "results"
RESULTS_DIR.mkdir(exist_ok=True)

# --- Window parameters ---
WINDOW_MONTHS = 120   # training window length
TEST_MONTHS   = 1     # test window length
STEP_MONTHS   = 1     # fold step size
MAX_FOLDS     = None  # set to a small int for a quick smoke test
RUN_BY        = "Jack"  # your name, recorded on every result row (default: OS user)
RESUME        = True  # True: skip runs already saved in results/ (e.g. after a crash or
                      # Colab disconnect). Keep False after changing a model's code.

# --- What to run ---
HORIZON_LIST  = [1, 3, 6]
TARGET_LIST   = ["INDPRO", "PAYEMS", "CPIAUCSL", "S&P 500"]
QUANTUM_TRACKS = ["Q_su_pce", "Q_su_pauli", "Q_su_bitstring", "Q_su_single_bit", "Q_heisenberg_pce",
                  "Q_heisenberg_pauli", "Q_heisenberg_single_bit", "Q_zz_pauli", "Q_zz_pce", "Q_zz_single_bit"]
ACTIVE_TRACKS = QUANTUM_TRACKS                                 # any keys of TRACK_CONFIG
ACTIVE_MODELS = ["decision_tree", "adaboost", "random_forest", "xgboost",
                 "linear_svm", "sig_kernel", "linear_readout",
                 "rnn", "gru", "lstm"]  # any keys of MODEL_REGISTRY

# --- Track registry: TRACK_CONFIG[track][target] = {"type", "path"} ---
TRACK_CONFIG = {
    "A":      shared_track("dataframe", DATA_DIR / "track_A_full.parquet", TARGET_LIST),
    "B":      {t: {"type": "dataframe", "path": DATA_DIR / f"track_b_{t}.parquet"} for t in TARGET_LIST},
    "C":      shared_track("pipeline", DATA_DIR / "track_C_pipe.pkl", TARGET_LIST),       # LASSO, tabled
    "D":      shared_track("pipeline", DATA_DIR / "track_D_pipe.pkl", TARGET_LIST),       # PCA ~30 factors
    "D_mini": shared_track("pipeline", DATA_DIR / "track_D_mini_pipe.pkl", TARGET_LIST),  # PCA 15 factors
    # reservoir tracks: built by scripts/build_quantum_tracks.py
    "QRC":    {t: {"type": "dataframe", "path": DATA_DIR / f"track_QRC_{t}.parquet"} for t in TARGET_LIST},
    "CRC":    {t: {"type": "dataframe", "path": DATA_DIR / f"track_CRC_{t}.parquet"} for t in TARGET_LIST},
    # quantum feature tracks: built by notebooks/quantum_data_prep.ipynb
    **{q: {t: {"type": "dataframe", "path": DATA_DIR / f"track_{q}_{t}.parquet"} for t in TARGET_LIST}
       for q in QUANTUM_TRACKS},
}

MODELS = {name: MODEL_REGISTRY[name] for name in ACTIVE_MODELS}

print(f"Window:   {WINDOW_MONTHS}m train / {TEST_MONTHS}m test / {STEP_MONTHS}m step")
print(f"Targets:  {TARGET_LIST}")
print(f"Horizons: {HORIZON_LIST}")
print(f"Tracks:   {ACTIVE_TRACKS}")
print(f"Models:   {ACTIVE_MODELS}")

Window:   120m train / 1m test / 1m step
Targets:  ['INDPRO', 'PAYEMS', 'CPIAUCSL', 'S&P 500']
Horizons: [1, 3, 6]
Tracks:   ['Q_su_pce', 'Q_su_pauli', 'Q_su_bitstring', 'Q_su_single_bit', 'Q_heisenberg_pce', 'Q_heisenberg_pauli', 'Q_heisenberg_single_bit', 'Q_zz_pauli', 'Q_zz_pce', 'Q_zz_single_bit']
Models:   ['decision_tree', 'adaboost', 'random_forest', 'xgboost', 'linear_svm', 'sig_kernel', 'linear_readout', 'rnn', 'gru', 'lstm']

## 3. Load data and build folds

In [4]:
track_data       = load_tracks(TRACK_CONFIG, ACTIVE_TRACKS, TARGET_LIST)
stationary_panel = pd.read_parquet(DATA_DIR / "stationary_panel.parquet")
targets          = pd.read_parquet(DATA_DIR / "targets.parquet")
usrec            = pd.read_parquet(DATA_DIR / "usrec.parquet")

print(f"Stationary panel {stationary_panel.shape}  {stationary_panel.index.min().date()} -> {stationary_panel.index.max().date()}")
print(f"Targets          {targets.shape}")

  Track Q_su_pce target INDPRO     loaded   shape=(767, 9)
  Track Q_su_pce target PAYEMS     loaded   shape=(767, 9)
  Track Q_su_pce target CPIAUCSL   loaded   shape=(767, 9)
  Track Q_su_pce target S&P 500    loaded   shape=(767, 9)
  Track Q_su_pauli target INDPRO     loaded   shape=(767, 15)
  Track Q_su_pauli target PAYEMS     loaded   shape=(767, 15)
  Track Q_su_pauli target CPIAUCSL   loaded   shape=(767, 18)
  Track Q_su_pauli target S&P 500    loaded   shape=(767, 18)
  Track Q_su_bitstring target INDPRO     loaded   shape=(767, 32)
  Track Q_su_bitstring target PAYEMS     loaded   shape=(767, 32)
  Track Q_su_bitstring target CPIAUCSL   loaded   shape=(767, 64)
  Track Q_su_bitstring target S&P 500    loaded   shape=(767, 64)
  Track Q_su_single_bit target INDPRO     loaded   shape=(767, 5)
  Track Q_su_single_bit target PAYEMS     loaded   shape=(767, 5)
  Track Q_su_single_bit target CPIAUCSL   loaded   shape=(767, 6)
  Track Q_su_single_bit target S&P 500    loaded   shape=(767, 6)
  Track Q_heisenberg_pce target INDPRO     loaded   shape=(767, 9)
  Track Q_heisenberg_pce target PAYEMS     loaded   shape=(767, 9)
  Track Q_heisenberg_pce target CPIAUCSL   loaded   shape=(767, 9)
  Track Q_heisenberg_pce target S&P 500    loaded   shape=(767, 9)
  Track Q_heisenberg_pauli target INDPRO     loaded   shape=(767, 33)
  Track Q_heisenberg_pauli target PAYEMS     loaded   shape=(767, 33)
  Track Q_heisenberg_pauli target CPIAUCSL   loaded   shape=(767, 39)
  Track Q_heisenberg_pauli target S&P 500    loaded   shape=(767, 39)
  Track Q_heisenberg_single_bit target INDPRO     loaded   shape=(767, 11)
  Track Q_heisenberg_single_bit target PAYEMS     loaded   shape=(767, 11)
  Track Q_heisenberg_single_bit target CPIAUCSL   loaded   shape=(767, 13)
  Track Q_heisenberg_single_bit target S&P 500    loaded   shape=(767, 13)
  Track Q_zz_pauli target INDPRO     loaded   shape=(767, 33)
  Track Q_zz_pauli target PAYEMS     loaded   shape=(767, 33)
  Track Q_zz_pauli target CPIAUCSL   loaded   shape=(767, 39)
  Track Q_zz_pauli target S&P 500    loaded   shape=(767, 39)
  Track Q_zz_pce target INDPRO     loaded   shape=(767, 9)
  Track Q_zz_pce target PAYEMS     loaded   shape=(767, 9)
  Track Q_zz_pce target CPIAUCSL   loaded   shape=(767, 9)
  Track Q_zz_pce target S&P 500    loaded   shape=(767, 9)
  Track Q_zz_single_bit target INDPRO     loaded   shape=(767, 11)

  Track Q_zz_single_bit target PAYEMS     loaded   shape=(767, 11)
  Track Q_zz_single_bit target CPIAUCSL   loaded   shape=(767, 13)
  Track Q_zz_single_bit target S&P 500    loaded   shape=(767, 13)
Stationary panel (767, 123)  1962-04-01 -> 2026-02-01
Targets          (806, 20)

In [5]:
# all feature panels share the stationary panel's monthly index
folds = generate_folds(stationary_panel.index, WINDOW_MONTHS, TEST_MONTHS, STEP_MONTHS)
if MAX_FOLDS is not None:
    folds = folds[:MAX_FOLDS]

print(f"Total folds: {len(folds)}")
print(f"  first: train {folds[0]['train_start'].date()} -> {folds[0]['train_end'].date()}, test {folds[0]['test_start'].date()}")
print(f"  last:  train {folds[-1]['train_start'].date()} -> {folds[-1]['train_end'].date()}, test {folds[-1]['test_start'].date()}")

Total folds: 647
  first: train 1962-04-01 -> 1972-03-01, test 1972-04-01
  last:  train 2016-02-01 -> 2026-01-01, test 2026-02-01

## 4. Run

Each track's results are saved to `results/raw/<model>/<track>.parquet` every 25 folds and when that track finishes. After a crash or disconnect, set `RESUME = True` and rerun: runs already saved are skipped.

In [6]:
results_df = run_evaluation(
    folds            = folds,
    tracks           = ACTIVE_TRACKS,
    targets          = TARGET_LIST,
    horizons         = HORIZON_LIST,
    models           = MODELS,
    targets_df       = targets,
    track_config     = TRACK_CONFIG,
    track_data       = track_data,
    stationary_panel = stationary_panel,
    run_by           = RUN_BY,
    results_dir      = RESULTS_DIR,  # checkpoint every 25 folds and at the end of each track
    resume           = RESUME,
)

n_err = results_df["error"].notna().sum()
print(f"Runs with errors: {n_err}")
if n_err:
    print(results_df.loc[results_df["error"].notna(), ["model", "track", "target", "error"]].drop_duplicates("error").head())

  Track Q_su_pce: resuming, 7724 runs already on disk will be skipped

  8724/776400 runs complete · 1m19s elapsed · ~16h50m left

  9724/776400 runs complete · 2m51s elapsed · ~18h13m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=300
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=300
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=300
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=300
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=300
  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=300
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=300
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=300
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=300

  10724/776400 runs complete · 4m19s elapsed · ~18h20m left

  11724/776400 runs complete · 5m33s elapsed · ~17h39m left

  12724/776400 runs complete · 11m11s elapsed · ~28h27m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=600
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=600
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=600
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=600
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=600

  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=600
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=600
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=600
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=600

  13724/776400 runs complete · 17m01s elapsed · ~36h03m left

  14724/776400 runs complete · 21m21s elapsed · ~38h43m left

  15724/776400 runs complete · 24m19s elapsed · ~38h31m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=900
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=900
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=900
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=900
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=900
  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=900
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=900

  Saved: raw/gru/Q_su_pce.parquet   new=300  total=900
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=900

  16724/776400 runs complete · 27m15s elapsed · ~38h20m left

  17724/776400 runs complete · 30m13s elapsed · ~38h12m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=1200
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=1200
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=1200
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=1200
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=1200
  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=1200

  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=1200
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=1200
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=1200

  18724/776400 runs complete · 32m58s elapsed · ~37h50m left

  19724/776400 runs complete · 35m31s elapsed · ~37h19m left

  20724/776400 runs complete · 37m54s elapsed · ~36h42m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=1500
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=1500
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=1500
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=1500
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=1500
  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=1500
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=1500
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=1500
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=1500

  21724/776400 runs complete · 39m46s elapsed · ~35h43m left

  22724/776400 runs complete · 42m20s elapsed · ~35h27m left

  23724/776400 runs complete · 44m40s elapsed · ~35h01m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=1800
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=1800
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=1800
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=1800
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=1800
  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=1800
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=1800

  Saved: raw/gru/Q_su_pce.parquet   new=300  total=1800
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=1800

  24724/776400 runs complete · 47m48s elapsed · ~35h13m left

  25724/776400 runs complete · 51m03s elapsed · ~35h29m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=2100
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=2100
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=2100
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=2100
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=2100
  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=2100

  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=2100
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=2100
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=2100

  26724/776400 runs complete · 53m56s elapsed · ~35h27m left

  27724/776400 runs complete · 56m45s elapsed · ~35h24m left

  28724/776400 runs complete · 1h00m elapsed · ~35h45m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=2400
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=2400
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=2400
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=2400
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=2400

  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=2400
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=2400
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=2400
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=2400

  29724/776400 runs complete · 1h03m elapsed · ~35h58m left

  30724/776400 runs complete · 1h06m elapsed · ~35h50m left

  31724/776400 runs complete · 1h09m elapsed · ~35h44m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=2700
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=2700
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=2700
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=2700
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=2700

  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=2700
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=2700
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=2700
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=2700

  32724/776400 runs complete · 1h12m elapsed · ~35h59m left

  33724/776400 runs complete · 1h15m elapsed · ~36h06m left

  34724/776400 runs complete · 1h18m elapsed · ~35h55m left
  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=3000
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=3000
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=3000
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=3000

  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=3000
  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=3000
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=3000
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=3000
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=3000

  35724/776400 runs complete · 1h20m elapsed · ~35h40m left

  36724/776400 runs complete · 1h23m elapsed · ~35h38m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=3300
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=3300
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=3300
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=3300
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=3300

  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=3300
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=3300
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=3300
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=3300

  37724/776400 runs complete · 1h27m elapsed · ~35h45m left

  38724/776400 runs complete · 1h30m elapsed · ~36h00m left

  39724/776400 runs complete · 1h34m elapsed · ~36h06m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=3600
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=3600
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=3600
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=3600
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=3600

  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=3600
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=3600
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=3600
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=3600

  40724/776400 runs complete · 1h37m elapsed · ~36h10m left

  41724/776400 runs complete · 1h40m elapsed · ~36h15m left

  42724/776400 runs complete · 1h44m elapsed · ~36h26m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=3900
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=3900
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=3900
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=3900
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=3900

  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=3900
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=3900
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=3900

  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=3900

  43724/776400 runs complete · 1h47m elapsed · ~36h20m left

  44724/776400 runs complete · 1h50m elapsed · ~36h17m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=4200
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=4200
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=4200
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=4200
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=4200

  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=4200
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=4200
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=4200
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=4200

  45724/776400 runs complete · 1h53m elapsed · ~36h14m left

  46724/776400 runs complete · 1h55m elapsed · ~36h02m left

  47724/776400 runs complete · 1h58m elapsed · ~35h56m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=4500
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=4500
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=4500
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=4500
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=4500

  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=4500
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=4500
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=4500
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=4500

  48724/776400 runs complete · 2h01m elapsed · ~35h48m left

  49724/776400 runs complete · 2h03m elapsed · ~35h42m left

  50724/776400 runs complete · 2h06m elapsed · ~35h40m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=4800
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=4800
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=4800
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=4800
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=4800

  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=4800
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=4800
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=4800
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=4800

  51724/776400 runs complete · 2h09m elapsed · ~35h36m left

  52724/776400 runs complete · 2h12m elapsed · ~35h31m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=5100
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=5100
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=5100
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=5100
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=5100

  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=5100
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=5100
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=5100
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=5100

  53724/776400 runs complete · 2h15m elapsed · ~35h32m left

  54724/776400 runs complete · 2h19m elapsed · ~35h35m left

  55724/776400 runs complete · 2h22m elapsed · ~35h41m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=5400
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=5400
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=5400
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=5400
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=5400

  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=5400
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=5400
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=5400
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=5400

  56724/776400 runs complete · 2h25m elapsed · ~35h43m left

  57724/776400 runs complete · 2h29m elapsed · ~35h45m left

  58724/776400 runs complete · 2h32m elapsed · ~35h44m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=5700
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=5700
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=5700
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=5700

  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=5700
  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=5700
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=5700
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=5700
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=5700

  59724/776400 runs complete · 2h35m elapsed · ~35h41m left

  60724/776400 runs complete · 2h38m elapsed · ~35h36m left

  61724/776400 runs complete · 2h41m elapsed · ~35h41m left
  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=6000
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=6000

  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=6000
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=6000
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=6000
  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=6000

  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=6000
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=6000
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=6000

  62724/776400 runs complete · 2h44m elapsed · ~35h40m left

  63724/776400 runs complete · 2h48m elapsed · ~35h40m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=6300
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=6300
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=6300
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=6300

  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=6300
  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=6300
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=6300
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=6300

  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=6300

  64724/776400 runs complete · 2h51m elapsed · ~35h37m left

  65724/776400 runs complete · 2h53m elapsed · ~35h26m left

  66724/776400 runs complete · 2h56m elapsed · ~35h21m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=6600
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=6600
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=6600
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=6600

  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=6600
  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=6600
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=6600
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=6600

  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=6600

  67724/776400 runs complete · 2h59m elapsed · ~35h14m left

  68724/776400 runs complete · 3h01m elapsed · ~35h04m left

  69724/776400 runs complete · 3h04m elapsed · ~35h01m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=6900
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=6900
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=6900
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=6900
  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=6900

  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=6900
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=6900
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=6900
  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=6900

  70724/776400 runs complete · 3h07m elapsed · ~35h02m left

  71724/776400 runs complete · 3h11m elapsed · ~35h05m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=7200
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=7200
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=7200
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=7200

  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=7200
  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=7200
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=7200
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=7200

  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=7200

  72724/776400 runs complete · 3h13m elapsed · ~34h58m left

  73724/776400 runs complete · 3h16m elapsed · ~34h55m left

  74724/776400 runs complete · 3h19m elapsed · ~34h49m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=300  total=7500
  Saved: raw/adaboost/Q_su_pce.parquet   new=300  total=7500
  Saved: raw/random_forest/Q_su_pce.parquet   new=300  total=7500
  Saved: raw/xgboost/Q_su_pce.parquet   new=300  total=7500

  Saved: raw/linear_svm/Q_su_pce.parquet   new=300  total=7500
  Saved: raw/sig_kernel/Q_su_pce.parquet   new=300  total=7500
  Saved: raw/rnn/Q_su_pce.parquet   new=300  total=7500
  Saved: raw/gru/Q_su_pce.parquet   new=300  total=7500

  Saved: raw/lstm/Q_su_pce.parquet   new=300  total=7500

  75724/776400 runs complete · 3h22m elapsed · ~34h43m left

  76724/776400 runs complete · 3h24m elapsed · ~34h36m left

  Saved: raw/decision_tree/Q_su_pce.parquet   new=224  total=7724
  Saved: raw/adaboost/Q_su_pce.parquet   new=224  total=7724
  Saved: raw/random_forest/Q_su_pce.parquet   new=224  total=7724
  Saved: raw/xgboost/Q_su_pce.parquet   new=224  total=7724

  Saved: raw/linear_svm/Q_su_pce.parquet   new=224  total=7724
  Saved: raw/sig_kernel/Q_su_pce.parquet   new=224  total=7724
  Saved: raw/rnn/Q_su_pce.parquet   new=224  total=7724
  Saved: raw/gru/Q_su_pce.parquet   new=224  total=7724

  Saved: raw/lstm/Q_su_pce.parquet   new=224  total=7724
  Track Q_su_pauli: resuming, 7724 runs already on disk will be skipped

  85448/776400 runs complete · 3h28m elapsed · ~34h13m left

  86448/776400 runs complete · 3h31m elapsed · ~34h13m left

  87448/776400 runs complete · 3h34m elapsed · ~34h12m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=300
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=300
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=300
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=300
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=300
  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=300
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=300
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=300
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=300

  88448/776400 runs complete · 3h37m elapsed · ~34h09m left

  89448/776400 runs complete · 3h40m elapsed · ~34h04m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=600
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=600
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=600
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=600
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=600
  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=600
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=600

  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=600
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=600

  90448/776400 runs complete · 3h43m elapsed · ~34h03m left

  91448/776400 runs complete · 3h46m elapsed · ~33h58m left

  92448/776400 runs complete · 3h48m elapsed · ~33h52m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=900
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=900
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=900
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=900
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=900
  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=900
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=900

  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=900
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=900

  93448/776400 runs complete · 3h51m elapsed · ~33h43m left

  94448/776400 runs complete · 3h53m elapsed · ~33h38m left

  95448/776400 runs complete · 3h56m elapsed · ~33h35m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=1200
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=1200
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=1200
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=1200
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=1200
  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=1200
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=1200
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=1200

  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=1200

  96448/776400 runs complete · 3h59m elapsed · ~33h31m left

  97448/776400 runs complete · 4h02m elapsed · ~33h31m left

  98448/776400 runs complete · 4h06m elapsed · ~33h34m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=1500
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=1500
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=1500
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=1500
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=1500
  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=1500
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=1500
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=1500

  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=1500

  99448/776400 runs complete · 4h09m elapsed · ~33h31m left

  100448/776400 runs complete · 4h11m elapsed · ~33h22m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=1800
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=1800
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=1800
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=1800
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=1800
  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=1800

  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=1800
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=1800
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=1800

  101448/776400 runs complete · 4h15m elapsed · ~33h22m left

  102448/776400 runs complete · 4h18m elapsed · ~33h21m left

  103448/776400 runs complete · 4h20m elapsed · ~33h15m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=2100
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=2100
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=2100
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=2100
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=2100
  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=2100

  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=2100
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=2100
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=2100

  104448/776400 runs complete · 4h23m elapsed · ~33h11m left

  105448/776400 runs complete · 4h27m elapsed · ~33h10m left

  106448/776400 runs complete · 4h30m elapsed · ~33h09m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=2400
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=2400
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=2400
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=2400
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=2400

  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=2400
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=2400
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=2400
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=2400

  107448/776400 runs complete · 4h33m elapsed · ~33h06m left

  108448/776400 runs complete · 4h35m elapsed · ~33h00m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=2700
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=2700
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=2700
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=2700
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=2700

  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=2700
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=2700
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=2700
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=2700

  109448/776400 runs complete · 4h38m elapsed · ~32h58m left

  110448/776400 runs complete · 4h41m elapsed · ~32h54m left

  111448/776400 runs complete · 4h45m elapsed · ~32h54m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=3000
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=3000
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=3000
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=3000
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=3000

  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=3000
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=3000
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=3000
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=3000

  112448/776400 runs complete · 4h47m elapsed · ~32h49m left

  113448/776400 runs complete · 4h50m elapsed · ~32h42m left

  114448/776400 runs complete · 4h52m elapsed · ~32h39m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=3300
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=3300
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=3300
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=3300
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=3300

  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=3300
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=3300
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=3300
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=3300

  115448/776400 runs complete · 4h56m elapsed · ~32h38m left

  116448/776400 runs complete · 4h59m elapsed · ~32h39m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=3600
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=3600
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=3600
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=3600
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=3600

  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=3600
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=3600
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=3600
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=3600

  117448/776400 runs complete · 5h03m elapsed · ~32h37m left

  118448/776400 runs complete · 5h06m elapsed · ~32h37m left

  119448/776400 runs complete · 5h10m elapsed · ~32h41m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=3900
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=3900
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=3900
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=3900
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=3900
  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=3900

  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=3900
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=3900
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=3900

  120448/776400 runs complete · 5h13m elapsed · ~32h39m left

  121448/776400 runs complete · 5h16m elapsed · ~32h33m left

  122448/776400 runs complete · 5h18m elapsed · ~32h28m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=4200
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=4200
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=4200
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=4200
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=4200

  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=4200
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=4200
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=4200
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=4200

  123448/776400 runs complete · 5h21m elapsed · ~32h22m left

  124448/776400 runs complete · 5h24m elapsed · ~32h18m left

  125448/776400 runs complete · 5h27m elapsed · ~32h15m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=4500
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=4500
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=4500
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=4500

  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=4500
  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=4500
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=4500
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=4500
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=4500

  126448/776400 runs complete · 5h29m elapsed · ~32h10m left

  127448/776400 runs complete · 5h32m elapsed · ~32h07m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=4800
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=4800
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=4800
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=4800
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=4800

  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=4800
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=4800
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=4800
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=4800

  128448/776400 runs complete · 5h36m elapsed · ~32h07m left

  129448/776400 runs complete · 5h39m elapsed · ~32h08m left

  130448/776400 runs complete · 5h43m elapsed · ~32h06m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=5100
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=5100
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=5100
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=5100
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=5100

  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=5100
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=5100
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=5100
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=5100

  131448/776400 runs complete · 5h46m elapsed · ~32h03m left

  132448/776400 runs complete · 5h49m elapsed · ~32h02m left

  133448/776400 runs complete · 5h52m elapsed · ~31h59m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=5400
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=5400
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=5400
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=5400
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=5400

  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=5400
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=5400
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=5400
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=5400

  134448/776400 runs complete · 5h55m elapsed · ~31h57m left

  135448/776400 runs complete · 5h58m elapsed · ~31h52m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=5700
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=5700
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=5700
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=5700
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=5700

  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=5700
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=5700
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=5700
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=5700

  136448/776400 runs complete · 6h01m elapsed · ~31h49m left

  137448/776400 runs complete · 6h04m elapsed · ~31h46m left

  138448/776400 runs complete · 6h06m elapsed · ~31h42m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=6000
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=6000
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=6000
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=6000

  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=6000
  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=6000
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=6000
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=6000

  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=6000

  139448/776400 runs complete · 6h09m elapsed · ~31h38m left

  140448/776400 runs complete · 6h11m elapsed · ~31h32m left

  141448/776400 runs complete · 6h14m elapsed · ~31h27m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=6300
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=6300
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=6300
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=6300
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=6300

  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=6300
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=6300
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=6300
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=6300

  142448/776400 runs complete · 6h17m elapsed · ~31h21m left

  143448/776400 runs complete · 6h19m elapsed · ~31h18m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=6600
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=6600
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=6600
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=6600
  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=6600

  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=6600
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=6600
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=6600
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=6600

  144448/776400 runs complete · 6h22m elapsed · ~31h16m left

  145448/776400 runs complete · 6h25m elapsed · ~31h10m left

  146448/776400 runs complete · 6h28m elapsed · ~31h05m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=6900
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=6900
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=6900
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=6900

  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=6900
  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=6900
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=6900
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=6900
  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=6900

  147448/776400 runs complete · 6h31m elapsed · ~31h03m left

  148448/776400 runs complete · 6h34m elapsed · ~31h02m left

  149448/776400 runs complete · 6h37m elapsed · ~30h59m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=7200
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=7200
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=7200
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=7200

  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=7200
  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=7200
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=7200
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=7200

  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=7200

  150448/776400 runs complete · 6h40m elapsed · ~30h57m left

  151448/776400 runs complete · 6h43m elapsed · ~30h54m left

  152448/776400 runs complete · 6h46m elapsed · ~30h49m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=300  total=7500
  Saved: raw/adaboost/Q_su_pauli.parquet   new=300  total=7500
  Saved: raw/random_forest/Q_su_pauli.parquet   new=300  total=7500
  Saved: raw/xgboost/Q_su_pauli.parquet   new=300  total=7500

  Saved: raw/linear_svm/Q_su_pauli.parquet   new=300  total=7500
  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=300  total=7500
  Saved: raw/rnn/Q_su_pauli.parquet   new=300  total=7500
  Saved: raw/gru/Q_su_pauli.parquet   new=300  total=7500

  Saved: raw/lstm/Q_su_pauli.parquet   new=300  total=7500

  153448/776400 runs complete · 6h48m elapsed · ~30h42m left

  154448/776400 runs complete · 6h50m elapsed · ~30h37m left

  Saved: raw/decision_tree/Q_su_pauli.parquet   new=224  total=7724
  Saved: raw/adaboost/Q_su_pauli.parquet   new=224  total=7724
  Saved: raw/random_forest/Q_su_pauli.parquet   new=224  total=7724
  Saved: raw/xgboost/Q_su_pauli.parquet   new=224  total=7724

  Saved: raw/linear_svm/Q_su_pauli.parquet   new=224  total=7724
  Saved: raw/sig_kernel/Q_su_pauli.parquet   new=224  total=7724
  Saved: raw/rnn/Q_su_pauli.parquet   new=224  total=7724
  Saved: raw/gru/Q_su_pauli.parquet   new=224  total=7724

  Saved: raw/lstm/Q_su_pauli.parquet   new=224  total=7724
  Track Q_su_bitstring: resuming, 7724 runs already on disk will be skipped

  163172/776400 runs complete · 6h53m elapsed · ~30h09m left

  164172/776400 runs complete · 6h55m elapsed · ~30h06m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=300
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=300
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=300
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=300
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=300
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=300
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=300
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=300
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=300

  165172/776400 runs complete · 6h59m elapsed · ~30h06m left

  166172/776400 runs complete · 7h03m elapsed · ~30h06m left

  167172/776400 runs complete · 7h06m elapsed · ~30h06m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=600
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=600
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=600
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=600
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=600
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=600
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=600
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=600

  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=600

  168172/776400 runs complete · 7h10m elapsed · ~30h04m left

  169172/776400 runs complete · 7h12m elapsed · ~29h58m left

  170172/776400 runs complete · 7h14m elapsed · ~29h53m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=900
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=900
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=900
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=900
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=900
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=900
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=900

  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=900
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=900

  171172/776400 runs complete · 7h17m elapsed · ~29h50m left

  172172/776400 runs complete · 7h20m elapsed · ~29h47m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=1200
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=1200
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=1200
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=1200
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=1200
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=1200

  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=1200
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=1200
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=1200

  173172/776400 runs complete · 7h23m elapsed · ~29h44m left

  174172/776400 runs complete · 7h26m elapsed · ~29h41m left

  175172/776400 runs complete · 7h29m elapsed · ~29h36m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=1500
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=1500
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=1500
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=1500
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=1500
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=1500
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=1500

  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=1500
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=1500

  176172/776400 runs complete · 7h31m elapsed · ~29h31m left

  177172/776400 runs complete · 7h34m elapsed · ~29h28m left

  178172/776400 runs complete · 7h38m elapsed · ~29h29m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=1800
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=1800
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=1800
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=1800
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=1800
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=1800
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=1800

  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=1800
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=1800

  179172/776400 runs complete · 7h41m elapsed · ~29h27m left

  180172/776400 runs complete · 7h44m elapsed · ~29h22m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=2100
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=2100
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=2100
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=2100
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=2100
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=2100
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=2100

  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=2100
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=2100

  181172/776400 runs complete · 7h46m elapsed · ~29h19m left

  182172/776400 runs complete · 7h49m elapsed · ~29h13m left

  183172/776400 runs complete · 7h50m elapsed · ~29h05m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=2400
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=2400
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=2400
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=2400
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=2400
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=2400
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=2400
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=2400
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=2400

  184172/776400 runs complete · 7h52m elapsed · ~28h56m left

  185172/776400 runs complete · 7h53m elapsed · ~28h47m left

  186172/776400 runs complete · 7h54m elapsed · ~28h38m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=2700
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=2700
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=2700
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=2700
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=2700
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=2700
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=2700
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=2700
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=2700

  187172/776400 runs complete · 7h56m elapsed · ~28h30m left

  188172/776400 runs complete · 7h57m elapsed · ~28h22m left

  189172/776400 runs complete · 7h58m elapsed · ~28h13m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=3000
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=3000
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=3000
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=3000
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=3000
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=3000
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=3000
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=3000
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=3000

  190172/776400 runs complete · 8h00m elapsed · ~28h05m left

  191172/776400 runs complete · 8h01m elapsed · ~27h58m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=3300
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=3300
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=3300
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=3300
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=3300
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=3300
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=3300
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=3300
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=3300

  192172/776400 runs complete · 8h03m elapsed · ~27h50m left

  193172/776400 runs complete · 8h04m elapsed · ~27h43m left

  194172/776400 runs complete · 8h06m elapsed · ~27h35m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=3600
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=3600
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=3600
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=3600
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=3600
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=3600
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=3600
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=3600
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=3600

  195172/776400 runs complete · 8h07m elapsed · ~27h27m left

  196172/776400 runs complete · 8h08m elapsed · ~27h19m left

  197172/776400 runs complete · 8h10m elapsed · ~27h12m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=3900
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=3900
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=3900
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=3900
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=3900
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=3900
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=3900
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=3900
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=3900

  198172/776400 runs complete · 8h11m elapsed · ~27h04m left

  199172/776400 runs complete · 8h12m elapsed · ~26h56m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=4200
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=4200
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=4200
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=4200
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=4200
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=4200
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=4200
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=4200

  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=4200

  200172/776400 runs complete · 8h14m elapsed · ~26h48m left

  201172/776400 runs complete · 8h15m elapsed · ~26h41m left

  202172/776400 runs complete · 8h16m elapsed · ~26h34m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=4500
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=4500
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=4500
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=4500
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=4500
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=4500
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=4500
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=4500
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=4500

  203172/776400 runs complete · 8h18m elapsed · ~26h27m left

  204172/776400 runs complete · 8h19m elapsed · ~26h20m left

  205172/776400 runs complete · 8h21m elapsed · ~26h13m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=4800
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=4800
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=4800
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=4800
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=4800
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=4800
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=4800

  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=4800
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=4800

  206172/776400 runs complete · 8h22m elapsed · ~26h06m left

  207172/776400 runs complete · 8h24m elapsed · ~25h59m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=5100
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=5100
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=5100
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=5100
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=5100
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=5100
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=5100
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=5100

  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=5100

  208172/776400 runs complete · 8h25m elapsed · ~25h53m left

  209172/776400 runs complete · 8h26m elapsed · ~25h45m left

  210172/776400 runs complete · 8h28m elapsed · ~25h39m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=5400
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=5400
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=5400
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=5400
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=5400
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=5400
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=5400

  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=5400
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=5400

  211172/776400 runs complete · 8h29m elapsed · ~25h32m left

  212172/776400 runs complete · 8h31m elapsed · ~25h26m left

  213172/776400 runs complete · 8h32m elapsed · ~25h19m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=5700
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=5700
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=5700
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=5700
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=5700
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=5700
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=5700

  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=5700
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=5700

  214172/776400 runs complete · 8h34m elapsed · ~25h13m left

  215172/776400 runs complete · 8h35m elapsed · ~25h06m left

  216172/776400 runs complete · 8h36m elapsed · ~24h59m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=6000
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=6000
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=6000
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=6000
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=6000
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=6000
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=6000
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=6000

  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=6000

  217172/776400 runs complete · 8h37m elapsed · ~24h52m left

  218172/776400 runs complete · 8h38m elapsed · ~24h45m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=6300
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=6300
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=6300
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=6300
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=6300
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=6300
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=6300

  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=6300
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=6300

  219172/776400 runs complete · 8h39m elapsed · ~24h38m left

  220172/776400 runs complete · 8h41m elapsed · ~24h31m left

  221172/776400 runs complete · 8h42m elapsed · ~24h25m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=6600
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=6600
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=6600
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=6600
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=6600
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=6600
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=6600
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=6600

  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=6600

  222172/776400 runs complete · 8h43m elapsed · ~24h18m left

  223172/776400 runs complete · 8h44m elapsed · ~24h12m left

  224172/776400 runs complete · 8h46m elapsed · ~24h06m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=6900
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=6900
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=6900
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=6900
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=6900
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=6900
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=6900

  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=6900
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=6900

  225172/776400 runs complete · 8h47m elapsed · ~24h00m left

  226172/776400 runs complete · 8h49m elapsed · ~23h54m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=7200
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=7200
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=7200
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=7200
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=7200
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=7200
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=7200
  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=7200

  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=7200

  227172/776400 runs complete · 8h50m elapsed · ~23h49m left

  228172/776400 runs complete · 8h52m elapsed · ~23h43m left

  229172/776400 runs complete · 8h53m elapsed · ~23h37m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=300  total=7500
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=300  total=7500
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=300  total=7500
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=300  total=7500
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=300  total=7500
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=300  total=7500
  Saved: raw/rnn/Q_su_bitstring.parquet   new=300  total=7500

  Saved: raw/gru/Q_su_bitstring.parquet   new=300  total=7500
  Saved: raw/lstm/Q_su_bitstring.parquet   new=300  total=7500

  230172/776400 runs complete · 8h54m elapsed · ~23h30m left

  231172/776400 runs complete · 8h55m elapsed · ~23h24m left

  Saved: raw/decision_tree/Q_su_bitstring.parquet   new=224  total=7724
  Saved: raw/adaboost/Q_su_bitstring.parquet   new=224  total=7724
  Saved: raw/random_forest/Q_su_bitstring.parquet   new=224  total=7724
  Saved: raw/xgboost/Q_su_bitstring.parquet   new=224  total=7724
  Saved: raw/linear_svm/Q_su_bitstring.parquet   new=224  total=7724
  Saved: raw/sig_kernel/Q_su_bitstring.parquet   new=224  total=7724
  Saved: raw/rnn/Q_su_bitstring.parquet   new=224  total=7724
  Saved: raw/gru/Q_su_bitstring.parquet   new=224  total=7724

  Saved: raw/lstm/Q_su_bitstring.parquet   new=224  total=7724
  Track Q_su_single_bit: resuming, 7724 runs already on disk will be skipped

  239896/776400 runs complete · 8h56m elapsed · ~22h58m left

  240896/776400 runs complete · 8h57m elapsed · ~22h51m left

  241896/776400 runs complete · 8h59m elapsed · ~22h46m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=300
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=300
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=300
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=300
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=300
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=300
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=300
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=300
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=300

  242896/776400 runs complete · 9h00m elapsed · ~22h40m left

  243896/776400 runs complete · 9h01m elapsed · ~22h34m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=600
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=600
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=600
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=600
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=600
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=600
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=600
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=600
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=600

  244896/776400 runs complete · 9h03m elapsed · ~22h29m left

  245896/776400 runs complete · 9h04m elapsed · ~22h24m left

  246896/776400 runs complete · 9h05m elapsed · ~22h18m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=900
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=900
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=900
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=900
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=900
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=900
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=900
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=900
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=900

  247896/776400 runs complete · 9h06m elapsed · ~22h11m left

  248896/776400 runs complete · 9h07m elapsed · ~22h05m left

  249896/776400 runs complete · 9h09m elapsed · ~22h00m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=1200
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=1200
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=1200
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=1200
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=1200
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=1200
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=1200
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=1200
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=1200

  250896/776400 runs complete · 9h10m elapsed · ~21h54m left

  251896/776400 runs complete · 9h11m elapsed · ~21h49m left

  252896/776400 runs complete · 9h12m elapsed · ~21h43m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=1500
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=1500
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=1500
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=1500
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=1500
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=1500
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=1500
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=1500
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=1500

  253896/776400 runs complete · 9h13m elapsed · ~21h37m left

  254896/776400 runs complete · 9h15m elapsed · ~21h32m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=1800
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=1800
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=1800
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=1800
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=1800
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=1800
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=1800
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=1800
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=1800

  255896/776400 runs complete · 9h16m elapsed · ~21h27m left

  256896/776400 runs complete · 9h17m elapsed · ~21h21m left

  257896/776400 runs complete · 9h18m elapsed · ~21h16m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=2100
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=2100
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=2100
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=2100
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=2100
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=2100
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=2100
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=2100
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=2100

  258896/776400 runs complete · 9h19m elapsed · ~21h11m left

  259896/776400 runs complete · 9h21m elapsed · ~21h05m left

  260896/776400 runs complete · 9h22m elapsed · ~21h00m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=2400
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=2400
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=2400
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=2400
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=2400
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=2400
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=2400
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=2400
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=2400

  261896/776400 runs complete · 9h23m elapsed · ~20h54m left

  262896/776400 runs complete · 9h24m elapsed · ~20h49m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=2700
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=2700
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=2700
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=2700
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=2700
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=2700
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=2700
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=2700
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=2700

  263896/776400 runs complete · 9h25m elapsed · ~20h44m left

  264896/776400 runs complete · 9h27m elapsed · ~20h39m left

  265896/776400 runs complete · 9h28m elapsed · ~20h34m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=3000
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=3000
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=3000

  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=3000
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=3000
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=3000
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=3000
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=3000
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=3000

  266896/776400 runs complete · 9h29m elapsed · ~20h29m left

  267896/776400 runs complete · 9h31m elapsed · ~20h25m left

  268896/776400 runs complete · 9h32m elapsed · ~20h20m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=3300
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=3300
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=3300
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=3300
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=3300
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=3300
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=3300
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=3300
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=3300

  269896/776400 runs complete · 9h33m elapsed · ~20h15m left

  270896/776400 runs complete · 9h35m elapsed · ~20h11m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=3600
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=3600
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=3600
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=3600
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=3600
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=3600
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=3600
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=3600
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=3600

  271896/776400 runs complete · 9h36m elapsed · ~20h07m left

  272896/776400 runs complete · 9h37m elapsed · ~20h02m left

  273896/776400 runs complete · 9h39m elapsed · ~19h57m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=3900
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=3900
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=3900
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=3900
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=3900
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=3900
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=3900
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=3900
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=3900

  274896/776400 runs complete · 9h40m elapsed · ~19h53m left

  275896/776400 runs complete · 9h41m elapsed · ~19h48m left

  276896/776400 runs complete · 9h42m elapsed · ~19h43m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=4200
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=4200
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=4200
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=4200
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=4200
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=4200
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=4200
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=4200
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=4200

  277896/776400 runs complete · 9h44m elapsed · ~19h38m left

  278896/776400 runs complete · 9h45m elapsed · ~19h33m left

  279896/776400 runs complete · 9h46m elapsed · ~19h29m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=4500
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=4500
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=4500
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=4500
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=4500
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=4500
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=4500
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=4500

  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=4500

  280896/776400 runs complete · 9h47m elapsed · ~19h24m left

  281896/776400 runs complete · 9h49m elapsed · ~19h20m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=4800
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=4800
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=4800
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=4800
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=4800
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=4800
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=4800
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=4800

  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=4800

  282896/776400 runs complete · 9h50m elapsed · ~19h16m left

  283896/776400 runs complete · 9h52m elapsed · ~19h12m left

  284896/776400 runs complete · 9h53m elapsed · ~19h08m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=5100
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=5100
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=5100
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=5100
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=5100
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=5100
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=5100
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=5100

  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=5100

  285896/776400 runs complete · 9h54m elapsed · ~19h04m left

  286896/776400 runs complete · 9h56m elapsed · ~19h00m left

  287896/776400 runs complete · 9h57m elapsed · ~18h55m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=5400
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=5400
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=5400
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=5400
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=5400
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=5400
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=5400
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=5400

  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=5400

  288896/776400 runs complete · 9h58m elapsed · ~18h51m left

  289896/776400 runs complete · 10h00m elapsed · ~18h47m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=5700
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=5700
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=5700
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=5700
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=5700
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=5700
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=5700
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=5700

  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=5700

  290896/776400 runs complete · 10h01m elapsed · ~18h43m left

  291896/776400 runs complete · 10h02m elapsed · ~18h39m left

  292896/776400 runs complete · 10h04m elapsed · ~18h34m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=6000
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=6000
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=6000
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=6000
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=6000
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=6000
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=6000

  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=6000
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=6000

  293896/776400 runs complete · 10h05m elapsed · ~18h30m left

  294896/776400 runs complete · 10h06m elapsed · ~18h25m left

  295896/776400 runs complete · 10h07m elapsed · ~18h21m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=6300
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=6300
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=6300
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=6300
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=6300
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=6300
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=6300
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=6300

  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=6300

  296896/776400 runs complete · 10h08m elapsed · ~18h17m left

  297896/776400 runs complete · 10h10m elapsed · ~18h13m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=6600
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=6600
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=6600
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=6600
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=6600
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=6600
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=6600

  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=6600
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=6600

  298896/776400 runs complete · 10h11m elapsed · ~18h09m left

  299896/776400 runs complete · 10h12m elapsed · ~18h04m left

  300896/776400 runs complete · 10h13m elapsed · ~18h00m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=6900
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=6900
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=6900
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=6900
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=6900
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=6900
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=6900
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=6900

  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=6900

  301896/776400 runs complete · 10h14m elapsed · ~17h56m left

  302896/776400 runs complete · 10h16m elapsed · ~17h52m left

  303896/776400 runs complete · 10h17m elapsed · ~17h48m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=7200
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=7200
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=7200
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=7200
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=7200
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=7200
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=7200
  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=7200

  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=7200

  304896/776400 runs complete · 10h18m elapsed · ~17h45m left

  305896/776400 runs complete · 10h20m elapsed · ~17h41m left

  306896/776400 runs complete · 10h21m elapsed · ~17h37m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=300  total=7500
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=300  total=7500
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=300  total=7500
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=300  total=7500
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=300  total=7500
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=300  total=7500
  Saved: raw/rnn/Q_su_single_bit.parquet   new=300  total=7500

  Saved: raw/gru/Q_su_single_bit.parquet   new=300  total=7500
  Saved: raw/lstm/Q_su_single_bit.parquet   new=300  total=7500

  307896/776400 runs complete · 10h22m elapsed · ~17h32m left

  308896/776400 runs complete · 10h23m elapsed · ~17h28m left

  Saved: raw/decision_tree/Q_su_single_bit.parquet   new=224  total=7724
  Saved: raw/adaboost/Q_su_single_bit.parquet   new=224  total=7724
  Saved: raw/random_forest/Q_su_single_bit.parquet   new=224  total=7724
  Saved: raw/xgboost/Q_su_single_bit.parquet   new=224  total=7724
  Saved: raw/linear_svm/Q_su_single_bit.parquet   new=224  total=7724
  Saved: raw/sig_kernel/Q_su_single_bit.parquet   new=224  total=7724

  Saved: raw/rnn/Q_su_single_bit.parquet   new=224  total=7724
  Saved: raw/gru/Q_su_single_bit.parquet   new=224  total=7724
  Saved: raw/lstm/Q_su_single_bit.parquet   new=224  total=7724
  Track Q_heisenberg_pce: resuming, 7724 runs already on disk will be skipped

  317620/776400 runs complete · 10h24m elapsed · ~17h07m left

  318620/776400 runs complete · 10h26m elapsed · ~17h03m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=300
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=300
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=300
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=300
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=300
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=300
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=300
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=300
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=300

  319620/776400 runs complete · 10h27m elapsed · ~17h00m left

  320620/776400 runs complete · 10h28m elapsed · ~16h55m left

  321620/776400 runs complete · 10h29m elapsed · ~16h52m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=600
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=600
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=600
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=600
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=600
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=600
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=600
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=600
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=600

  322620/776400 runs complete · 10h31m elapsed · ~16h48m left

  323620/776400 runs complete · 10h32m elapsed · ~16h44m left

  324620/776400 runs complete · 10h33m elapsed · ~16h41m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=900
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=900
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=900
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=900
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=900
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=900
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=900
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=900
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=900

  325620/776400 runs complete · 10h35m elapsed · ~16h37m left

  326620/776400 runs complete · 10h36m elapsed · ~16h33m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=1200
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=1200
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=1200
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=1200
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=1200
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=1200
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=1200
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=1200
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=1200

  327620/776400 runs complete · 10h37m elapsed · ~16h30m left

  328620/776400 runs complete · 10h39m elapsed · ~16h26m left

  329620/776400 runs complete · 10h40m elapsed · ~16h23m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=1500
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=1500
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=1500
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=1500
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=1500
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=1500
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=1500
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=1500
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=1500

  330620/776400 runs complete · 10h41m elapsed · ~16h19m left

  331620/776400 runs complete · 10h42m elapsed · ~16h15m left

  332620/776400 runs complete · 10h43m elapsed · ~16h11m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=1800
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=1800
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=1800
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=1800
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=1800
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=1800
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=1800
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=1800
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=1800

  333620/776400 runs complete · 10h44m elapsed · ~16h08m left

  334620/776400 runs complete · 10h46m elapsed · ~16h04m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=2100
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=2100
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=2100
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=2100
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=2100
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=2100
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=2100
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=2100
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=2100

  335620/776400 runs complete · 10h47m elapsed · ~16h00m left

  336620/776400 runs complete · 10h48m elapsed · ~15h57m left

  337620/776400 runs complete · 10h49m elapsed · ~15h53m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=2400
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=2400
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=2400
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=2400
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=2400
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=2400
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=2400
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=2400
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=2400

  338620/776400 runs complete · 10h51m elapsed · ~15h50m left

  339620/776400 runs complete · 10h52m elapsed · ~15h47m left

  340620/776400 runs complete · 10h53m elapsed · ~15h43m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=2700
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=2700
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=2700
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=2700
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=2700
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=2700
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=2700
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=2700
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=2700

  341620/776400 runs complete · 10h54m elapsed · ~15h39m left

  342620/776400 runs complete · 10h55m elapsed · ~15h35m left

  343620/776400 runs complete · 10h57m elapsed · ~15h32m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=3000
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=3000
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=3000
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=3000
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=3000
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=3000
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=3000
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=3000
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=3000

  344620/776400 runs complete · 10h58m elapsed · ~15h29m left

  345620/776400 runs complete · 10h59m elapsed · ~15h25m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=3300
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=3300
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=3300
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=3300
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=3300
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=3300
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=3300
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=3300
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=3300

  346620/776400 runs complete · 11h00m elapsed · ~15h21m left

  347620/776400 runs complete · 11h02m elapsed · ~15h18m left

  348620/776400 runs complete · 11h03m elapsed · ~15h15m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=3600
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=3600
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=3600
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=3600
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=3600
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=3600
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=3600
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=3600
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=3600

  349620/776400 runs complete · 11h04m elapsed · ~15h12m left

  350620/776400 runs complete · 11h06m elapsed · ~15h09m left

  351620/776400 runs complete · 11h07m elapsed · ~15h05m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=3900
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=3900
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=3900
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=3900
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=3900
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=3900
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=3900
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=3900

  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=3900

  352620/776400 runs complete · 11h08m elapsed · ~15h02m left

  353620/776400 runs complete · 11h09m elapsed · ~14h58m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=4200
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=4200
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=4200
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=4200
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=4200
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=4200
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=4200
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=4200
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=4200

  354620/776400 runs complete · 11h10m elapsed · ~14h55m left

  355620/776400 runs complete · 11h11m elapsed · ~14h51m left

  356620/776400 runs complete · 11h13m elapsed · ~14h48m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=4500
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=4500
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=4500
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=4500
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=4500
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=4500
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=4500
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=4500
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=4500

  357620/776400 runs complete · 11h14m elapsed · ~14h45m left

  358620/776400 runs complete · 11h15m elapsed · ~14h42m left

  359620/776400 runs complete · 11h16m elapsed · ~14h38m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=4800
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=4800
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=4800
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=4800
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=4800
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=4800
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=4800
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=4800
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=4800

  360620/776400 runs complete · 11h18m elapsed · ~14h35m left

  361620/776400 runs complete · 11h19m elapsed · ~14h32m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=5100
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=5100
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=5100
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=5100
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=5100
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=5100
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=5100
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=5100
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=5100

  362620/776400 runs complete · 11h21m elapsed · ~14h29m left

  363620/776400 runs complete · 11h22m elapsed · ~14h26m left

  364620/776400 runs complete · 11h23m elapsed · ~14h23m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=5400
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=5400
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=5400
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=5400
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=5400
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=5400
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=5400

  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=5400
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=5400

  365620/776400 runs complete · 11h24m elapsed · ~14h20m left

  366620/776400 runs complete · 11h26m elapsed · ~14h17m left

  367620/776400 runs complete · 11h27m elapsed · ~14h14m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=5700
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=5700
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=5700
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=5700
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=5700
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=5700
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=5700

  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=5700
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=5700

  368620/776400 runs complete · 11h28m elapsed · ~14h11m left

  369620/776400 runs complete · 11h30m elapsed · ~14h08m left

  370620/776400 runs complete · 11h31m elapsed · ~14h05m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=6000
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=6000
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=6000
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=6000
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=6000
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=6000
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=6000
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=6000

  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=6000

  371620/776400 runs complete · 11h32m elapsed · ~14h02m left

  372620/776400 runs complete · 11h34m elapsed · ~13h59m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=6300
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=6300
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=6300
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=6300
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=6300
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=6300
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=6300
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=6300

  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=6300

  373620/776400 runs complete · 11h35m elapsed · ~13h56m left

  374620/776400 runs complete · 11h36m elapsed · ~13h53m left

  375620/776400 runs complete · 11h38m elapsed · ~13h50m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=6600
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=6600
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=6600
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=6600
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=6600
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=6600
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=6600
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=6600

  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=6600

  376620/776400 runs complete · 11h39m elapsed · ~13h47m left

  377620/776400 runs complete · 11h40m elapsed · ~13h44m left

  378620/776400 runs complete · 11h41m elapsed · ~13h41m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=6900
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=6900
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=6900
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=6900
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=6900
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=6900
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=6900

  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=6900
  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=6900

  379620/776400 runs complete · 11h43m elapsed · ~13h38m left

  380620/776400 runs complete · 11h44m elapsed · ~13h35m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=7200
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=7200
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=7200
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=7200
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=7200
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=7200
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=7200
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=7200

  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=7200

  381620/776400 runs complete · 11h45m elapsed · ~13h32m left

  382620/776400 runs complete · 11h47m elapsed · ~13h29m left

  383620/776400 runs complete · 11h48m elapsed · ~13h26m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=300  total=7500
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=300  total=7500
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=300  total=7500
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=300  total=7500
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=300  total=7500
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=300  total=7500
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=300  total=7500
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=300  total=7500

  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=300  total=7500

  384620/776400 runs complete · 11h49m elapsed · ~13h23m left

  385620/776400 runs complete · 11h50m elapsed · ~13h20m left

  Saved: raw/decision_tree/Q_heisenberg_pce.parquet   new=224  total=7724
  Saved: raw/adaboost/Q_heisenberg_pce.parquet   new=224  total=7724
  Saved: raw/random_forest/Q_heisenberg_pce.parquet   new=224  total=7724
  Saved: raw/xgboost/Q_heisenberg_pce.parquet   new=224  total=7724
  Saved: raw/linear_svm/Q_heisenberg_pce.parquet   new=224  total=7724
  Saved: raw/sig_kernel/Q_heisenberg_pce.parquet   new=224  total=7724
  Saved: raw/rnn/Q_heisenberg_pce.parquet   new=224  total=7724
  Saved: raw/gru/Q_heisenberg_pce.parquet   new=224  total=7724

  Saved: raw/lstm/Q_heisenberg_pce.parquet   new=224  total=7724

  386620/776400 runs complete · 11h52m elapsed · ~13h17m left

  387620/776400 runs complete · 11h53m elapsed · ~13h14m left

  388620/776400 runs complete · 11h54m elapsed · ~13h11m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=300
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=300
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=300
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=300
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=300
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=300
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=300
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=300
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=300
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=300

  389620/776400 runs complete · 11h55m elapsed · ~13h08m left

  390620/776400 runs complete · 11h57m elapsed · ~13h05m left

  391620/776400 runs complete · 11h58m elapsed · ~13h03m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=600
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=600
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=600
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=600
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=600
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=600
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=600
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=600
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=600
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=600

  392620/776400 runs complete · 11h59m elapsed · ~13h00m left

  393620/776400 runs complete · 12h01m elapsed · ~12h57m left

  394620/776400 runs complete · 12h02m elapsed · ~12h54m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=900
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=900
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=900
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=900
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=900
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=900
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=900
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=900
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=900
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=900

  395620/776400 runs complete · 12h03m elapsed · ~12h52m left

  396620/776400 runs complete · 12h05m elapsed · ~12h49m left

  397620/776400 runs complete · 12h06m elapsed · ~12h46m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=1200
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=1200
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=1200
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=1200
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=1200
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=1200
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=1200
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=1200
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=1200
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=1200

  398620/776400 runs complete · 12h07m elapsed · ~12h43m left

  399620/776400 runs complete · 12h08m elapsed · ~12h40m left

  400620/776400 runs complete · 12h09m elapsed · ~12h37m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=1500
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=1500
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=1500
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=1500
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=1500
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=1500
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=1500
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=1500
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=1500
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=1500

  401620/776400 runs complete · 12h10m elapsed · ~12h34m left

  402620/776400 runs complete · 12h12m elapsed · ~12h31m left

  403620/776400 runs complete · 12h13m elapsed · ~12h29m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=1800
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=1800
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=1800
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=1800
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=1800
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=1800
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=1800
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=1800
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=1800
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=1800

  404620/776400 runs complete · 12h15m elapsed · ~12h26m left

  405620/776400 runs complete · 12h16m elapsed · ~12h24m left

  406620/776400 runs complete · 12h17m elapsed · ~12h21m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=2100
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=2100
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=2100
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=2100
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=2100
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=2100
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=2100
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=2100
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=2100
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=2100

  407620/776400 runs complete · 12h18m elapsed · ~12h18m left

  408620/776400 runs complete · 12h20m elapsed · ~12h15m left

  409620/776400 runs complete · 12h21m elapsed · ~12h13m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=2400
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=2400
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=2400
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=2400
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=2400
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=2400
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=2400
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=2400
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=2400
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=2400

  410620/776400 runs complete · 12h23m elapsed · ~12h10m left

  411620/776400 runs complete · 12h24m elapsed · ~12h07m left

  412620/776400 runs complete · 12h25m elapsed · ~12h05m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=2700
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=2700
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=2700
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=2700
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=2700
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=2700
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=2700
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=2700
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=2700

  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=2700

  413620/776400 runs complete · 12h26m elapsed · ~12h02m left

  414620/776400 runs complete · 12h28m elapsed · ~11h59m left

  415620/776400 runs complete · 12h29m elapsed · ~11h57m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=3000
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=3000
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=3000
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=3000
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=3000
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=3000
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=3000
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=3000
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=3000
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=3000

  416620/776400 runs complete · 12h31m elapsed · ~11h54m left

  417620/776400 runs complete · 12h32m elapsed · ~11h52m left

  418620/776400 runs complete · 12h33m elapsed · ~11h49m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=3300
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=3300
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=3300
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=3300
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=3300
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=3300
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=3300
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=3300
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=3300
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=3300

  419620/776400 runs complete · 12h34m elapsed · ~11h46m left

  420620/776400 runs complete · 12h36m elapsed · ~11h44m left

  421620/776400 runs complete · 12h38m elapsed · ~11h42m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=3600
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=3600
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=3600
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=3600
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=3600
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=3600
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=3600
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=3600
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=3600
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=3600

  422620/776400 runs complete · 12h39m elapsed · ~11h39m left

  423620/776400 runs complete · 12h41m elapsed · ~11h37m left

  424620/776400 runs complete · 12h42m elapsed · ~11h35m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=3900
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=3900
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=3900
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=3900
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=3900
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=3900
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=3900
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=3900

  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=3900
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=3900

  425620/776400 runs complete · 12h44m elapsed · ~11h32m left

  426620/776400 runs complete · 12h45m elapsed · ~11h29m left

  427620/776400 runs complete · 12h46m elapsed · ~11h27m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=4200
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=4200
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=4200
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=4200
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=4200
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=4200
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=4200
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=4200
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=4200

  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=4200

  428620/776400 runs complete · 12h47m elapsed · ~11h24m left

  429620/776400 runs complete · 12h49m elapsed · ~11h22m left

  430620/776400 runs complete · 12h50m elapsed · ~11h19m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=4500
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=4500
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=4500
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=4500
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=4500
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=4500
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=4500
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=4500
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=4500

  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=4500

  431620/776400 runs complete · 12h52m elapsed · ~11h17m left

  432620/776400 runs complete · 12h53m elapsed · ~11h14m left

  433620/776400 runs complete · 12h54m elapsed · ~11h12m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=4800
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=4800
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=4800
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=4800
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=4800
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=4800
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=4800
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=4800

  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=4800
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=4800

  434620/776400 runs complete · 12h55m elapsed · ~11h09m left

  435620/776400 runs complete · 12h56m elapsed · ~11h06m left

  436620/776400 runs complete · 12h57m elapsed · ~11h04m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=5100
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=5100
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=5100
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=5100
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=5100
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=5100
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=5100
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=5100
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=5100

  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=5100

  437620/776400 runs complete · 12h59m elapsed · ~11h01m left

  438620/776400 runs complete · 13h00m elapsed · ~10h59m left

  439620/776400 runs complete · 13h01m elapsed · ~10h56m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=5400
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=5400
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=5400
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=5400
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=5400
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=5400
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=5400
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=5400

  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=5400
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=5400

  440620/776400 runs complete · 13h03m elapsed · ~10h54m left

  441620/776400 runs complete · 13h05m elapsed · ~10h52m left

  442620/776400 runs complete · 13h06m elapsed · ~10h49m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=5700
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=5700
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=5700
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=5700
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=5700
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=5700
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=5700
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=5700

  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=5700
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=5700

  443620/776400 runs complete · 13h07m elapsed · ~10h46m left

  444620/776400 runs complete · 13h08m elapsed · ~10h44m left

  445620/776400 runs complete · 13h10m elapsed · ~10h42m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=6000
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=6000
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=6000
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=6000
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=6000
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=6000
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=6000
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=6000

  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=6000
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=6000

  446620/776400 runs complete · 13h11m elapsed · ~10h39m left

  447620/776400 runs complete · 13h13m elapsed · ~10h37m left

  448620/776400 runs complete · 13h14m elapsed · ~10h35m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=6300
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=6300
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=6300
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=6300
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=6300
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=6300
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=6300

  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=6300
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=6300
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=6300

  449620/776400 runs complete · 13h15m elapsed · ~10h32m left

  450620/776400 runs complete · 13h16m elapsed · ~10h30m left

  451620/776400 runs complete · 13h18m elapsed · ~10h27m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=6600
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=6600
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=6600
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=6600
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=6600
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=6600
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=6600
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=6600

  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=6600
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=6600

  452620/776400 runs complete · 13h19m elapsed · ~10h25m left

  453620/776400 runs complete · 13h20m elapsed · ~10h22m left

  454620/776400 runs complete · 13h21m elapsed · ~10h20m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=6900
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=6900
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=6900
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=6900
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=6900
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=6900
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=6900
  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=6900

  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=6900
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=6900

  455620/776400 runs complete · 13h23m elapsed · ~10h17m left

  456620/776400 runs complete · 13h24m elapsed · ~10h15m left

  457620/776400 runs complete · 13h25m elapsed · ~10h13m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=7200
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=7200
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=7200
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=7200
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=7200
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=7200
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=7200

  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=7200
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=7200
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=7200

  458620/776400 runs complete · 13h27m elapsed · ~10h10m left

  459620/776400 runs complete · 13h28m elapsed · ~10h08m left

  460620/776400 runs complete · 13h29m elapsed · ~10h05m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=300  total=7500
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=300  total=7500
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=300  total=7500
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=300  total=7500
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=300  total=7500
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=300  total=7500
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=300  total=7500

  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=300  total=7500
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=300  total=7500
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=300  total=7500

  461620/776400 runs complete · 13h30m elapsed · ~10h03m left

  462620/776400 runs complete · 13h31m elapsed · ~10h00m left

  Saved: raw/decision_tree/Q_heisenberg_pauli.parquet   new=224  total=7724
  Saved: raw/adaboost/Q_heisenberg_pauli.parquet   new=224  total=7724
  Saved: raw/random_forest/Q_heisenberg_pauli.parquet   new=224  total=7724
  Saved: raw/xgboost/Q_heisenberg_pauli.parquet   new=224  total=7724
  Saved: raw/linear_svm/Q_heisenberg_pauli.parquet   new=224  total=7724
  Saved: raw/sig_kernel/Q_heisenberg_pauli.parquet   new=224  total=7724
  Saved: raw/linear_readout/Q_heisenberg_pauli.parquet   new=224  total=7724

  Saved: raw/rnn/Q_heisenberg_pauli.parquet   new=224  total=7724
  Saved: raw/gru/Q_heisenberg_pauli.parquet   new=224  total=7724
  Saved: raw/lstm/Q_heisenberg_pauli.parquet   new=224  total=7724

  463620/776400 runs complete · 13h32m elapsed · ~9h58m left

  464620/776400 runs complete · 13h34m elapsed · ~9h55m left

  465620/776400 runs complete · 13h35m elapsed · ~9h53m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=300
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=300
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=300
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=300
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=300
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=300
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=300
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=300
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=300
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=300

  466620/776400 runs complete · 13h36m elapsed · ~9h51m left

  467620/776400 runs complete · 13h38m elapsed · ~9h48m left

  468620/776400 runs complete · 13h39m elapsed · ~9h46m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=600
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=600
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=600
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=600
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=600
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=600
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=600
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=600
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=600
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=600

  469620/776400 runs complete · 13h40m elapsed · ~9h44m left

  470620/776400 runs complete · 13h42m elapsed · ~9h42m left

  471620/776400 runs complete · 13h43m elapsed · ~9h39m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=900
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=900
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=900
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=900
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=900
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=900
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=900
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=900
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=900
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=900

  472620/776400 runs complete · 13h44m elapsed · ~9h37m left

  473620/776400 runs complete · 13h45m elapsed · ~9h34m left

  474620/776400 runs complete · 13h46m elapsed · ~9h32m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=1200
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=1200
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=1200
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=1200
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=1200
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=1200
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=1200
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=1200
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=1200
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=1200

  475620/776400 runs complete · 13h47m elapsed · ~9h29m left

  476620/776400 runs complete · 13h49m elapsed · ~9h27m left

  477620/776400 runs complete · 13h50m elapsed · ~9h25m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=1500
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=1500
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=1500
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=1500
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=1500
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=1500
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=1500
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=1500
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=1500
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=1500

  478620/776400 runs complete · 13h51m elapsed · ~9h22m left

  479620/776400 runs complete · 13h52m elapsed · ~9h20m left

  480620/776400 runs complete · 13h54m elapsed · ~9h18m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=1800
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=1800
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=1800
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=1800
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=1800
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=1800
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=1800
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=1800
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=1800
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=1800

  481620/776400 runs complete · 13h55m elapsed · ~9h15m left

  482620/776400 runs complete · 13h56m elapsed · ~9h13m left

  483620/776400 runs complete · 13h57m elapsed · ~9h10m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=2100
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=2100
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=2100
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=2100
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=2100
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=2100
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=2100
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=2100
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=2100
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=2100

  484620/776400 runs complete · 13h58m elapsed · ~9h08m left

  485620/776400 runs complete · 13h59m elapsed · ~9h06m left

  486620/776400 runs complete · 14h00m elapsed · ~9h03m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=2400
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=2400
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=2400
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=2400
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=2400
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=2400
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=2400
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=2400
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=2400
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=2400

  487620/776400 runs complete · 14h02m elapsed · ~9h01m left

  488620/776400 runs complete · 14h03m elapsed · ~8h59m left

  489620/776400 runs complete · 14h04m elapsed · ~8h56m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=2700
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=2700
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=2700
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=2700
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=2700
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=2700
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=2700
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=2700
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=2700
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=2700

  490620/776400 runs complete · 14h05m elapsed · ~8h54m left

  491620/776400 runs complete · 14h06m elapsed · ~8h52m left

  492620/776400 runs complete · 14h08m elapsed · ~8h50m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=3000
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=3000
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=3000
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=3000
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=3000
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=3000
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=3000
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=3000
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=3000
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=3000

  493620/776400 runs complete · 14h09m elapsed · ~8h47m left

  494620/776400 runs complete · 14h10m elapsed · ~8h45m left

  495620/776400 runs complete · 14h11m elapsed · ~8h43m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=3300
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=3300
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=3300
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=3300
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=3300
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=3300
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=3300
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=3300
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=3300
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=3300

  496620/776400 runs complete · 14h12m elapsed · ~8h40m left

  497620/776400 runs complete · 14h14m elapsed · ~8h38m left

  498620/776400 runs complete · 14h15m elapsed · ~8h36m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=3600
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=3600
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=3600
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=3600
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=3600
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=3600
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=3600
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=3600
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=3600

  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=3600

  499620/776400 runs complete · 14h16m elapsed · ~8h34m left

  500620/776400 runs complete · 14h18m elapsed · ~8h32m left

  501620/776400 runs complete · 14h19m elapsed · ~8h30m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=3900
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=3900
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=3900
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=3900
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=3900
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=3900
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=3900
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=3900
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=3900

  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=3900

  502620/776400 runs complete · 14h20m elapsed · ~8h27m left

  503620/776400 runs complete · 14h21m elapsed · ~8h25m left

  504620/776400 runs complete · 14h22m elapsed · ~8h23m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=4200
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=4200
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=4200
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=4200
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=4200
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=4200
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=4200
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=4200
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=4200

  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=4200

  505620/776400 runs complete · 14h23m elapsed · ~8h20m left

  506620/776400 runs complete · 14h24m elapsed · ~8h18m left

  507620/776400 runs complete · 14h26m elapsed · ~8h16m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=4500
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=4500
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=4500
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=4500
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=4500
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=4500
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=4500
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=4500

  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=4500
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=4500

  508620/776400 runs complete · 14h27m elapsed · ~8h14m left

  509620/776400 runs complete · 14h28m elapsed · ~8h11m left

  510620/776400 runs complete · 14h29m elapsed · ~8h09m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=4800
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=4800
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=4800
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=4800
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=4800
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=4800
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=4800
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=4800

  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=4800
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=4800

  511620/776400 runs complete · 14h30m elapsed · ~8h07m left

  512620/776400 runs complete · 14h31m elapsed · ~8h05m left

  513620/776400 runs complete · 14h33m elapsed · ~8h03m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=5100
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=5100
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=5100
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=5100
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=5100
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=5100
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=5100
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=5100
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=5100

  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=5100

  514620/776400 runs complete · 14h34m elapsed · ~8h00m left

  515620/776400 runs complete · 14h35m elapsed · ~7h58m left

  516620/776400 runs complete · 14h36m elapsed · ~7h56m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=5400
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=5400
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=5400
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=5400
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=5400
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=5400
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=5400
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=5400

  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=5400
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=5400

  517620/776400 runs complete · 14h37m elapsed · ~7h54m left

  518620/776400 runs complete · 14h39m elapsed · ~7h52m left

  519620/776400 runs complete · 14h40m elapsed · ~7h49m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=5700
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=5700
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=5700
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=5700
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=5700
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=5700
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=5700

  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=5700
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=5700
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=5700

  520620/776400 runs complete · 14h41m elapsed · ~7h47m left

  521620/776400 runs complete · 14h42m elapsed · ~7h45m left

  522620/776400 runs complete · 14h44m elapsed · ~7h43m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=6000
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=6000
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=6000
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=6000
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=6000
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=6000
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=6000
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=6000

  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=6000
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=6000

  523620/776400 runs complete · 14h45m elapsed · ~7h41m left

  524620/776400 runs complete · 14h46m elapsed · ~7h39m left

  525620/776400 runs complete · 14h47m elapsed · ~7h37m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=6300
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=6300
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=6300
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=6300
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=6300
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=6300
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=6300
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=6300

  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=6300
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=6300

  526620/776400 runs complete · 14h49m elapsed · ~7h35m left

  527620/776400 runs complete · 14h50m elapsed · ~7h32m left

  528620/776400 runs complete · 14h51m elapsed · ~7h30m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=6600
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=6600
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=6600
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=6600
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=6600
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=6600
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=6600

  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=6600
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=6600
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=6600

  529620/776400 runs complete · 14h52m elapsed · ~7h28m left

  530620/776400 runs complete · 14h53m elapsed · ~7h26m left

  531620/776400 runs complete · 14h54m elapsed · ~7h24m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=6900
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=6900
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=6900
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=6900
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=6900
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=6900
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=6900

  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=6900
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=6900
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=6900

  532620/776400 runs complete · 14h55m elapsed · ~7h22m left

  533620/776400 runs complete · 14h57m elapsed · ~7h19m left

  534620/776400 runs complete · 14h58m elapsed · ~7h17m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=7200
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=7200
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=7200
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=7200
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=7200
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=7200
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=7200
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=7200

  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=7200
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=7200

  535620/776400 runs complete · 14h59m elapsed · ~7h15m left

  536620/776400 runs complete · 15h00m elapsed · ~7h13m left

  537620/776400 runs complete · 15h01m elapsed · ~7h11m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=300  total=7500
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=300  total=7500
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=300  total=7500
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=300  total=7500
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=300  total=7500
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=300  total=7500
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=300  total=7500
  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=300  total=7500

  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=300  total=7500
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=300  total=7500

  538620/776400 runs complete · 15h03m elapsed · ~7h09m left

  539620/776400 runs complete · 15h04m elapsed · ~7h07m left

  540620/776400 runs complete · 15h05m elapsed · ~7h05m left

  Saved: raw/decision_tree/Q_heisenberg_single_bit.parquet   new=224  total=7724
  Saved: raw/adaboost/Q_heisenberg_single_bit.parquet   new=224  total=7724
  Saved: raw/random_forest/Q_heisenberg_single_bit.parquet   new=224  total=7724
  Saved: raw/xgboost/Q_heisenberg_single_bit.parquet   new=224  total=7724
  Saved: raw/linear_svm/Q_heisenberg_single_bit.parquet   new=224  total=7724
  Saved: raw/sig_kernel/Q_heisenberg_single_bit.parquet   new=224  total=7724
  Saved: raw/linear_readout/Q_heisenberg_single_bit.parquet   new=224  total=7724

  Saved: raw/rnn/Q_heisenberg_single_bit.parquet   new=224  total=7724
  Saved: raw/gru/Q_heisenberg_single_bit.parquet   new=224  total=7724
  Saved: raw/lstm/Q_heisenberg_single_bit.parquet   new=224  total=7724

  541620/776400 runs complete · 15h06m elapsed · ~7h03m left

  542620/776400 runs complete · 15h07m elapsed · ~7h01m left

  543620/776400 runs complete · 15h08m elapsed · ~6h58m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=300
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=300
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=300
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=300
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=300
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=300
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=300
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=300
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=300
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=300

  544620/776400 runs complete · 15h10m elapsed · ~6h56m left

  545620/776400 runs complete · 15h11m elapsed · ~6h54m left

  546620/776400 runs complete · 15h12m elapsed · ~6h52m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=600
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=600
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=600
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=600
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=600
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=600
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=600
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=600
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=600
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=600

  547620/776400 runs complete · 15h13m elapsed · ~6h50m left

  548620/776400 runs complete · 15h15m elapsed · ~6h48m left

  549620/776400 runs complete · 15h16m elapsed · ~6h46m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=900
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=900
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=900
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=900
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=900
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=900
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=900
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=900
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=900
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=900

  550620/776400 runs complete · 15h17m elapsed · ~6h44m left

  551620/776400 runs complete · 15h18m elapsed · ~6h42m left

  552620/776400 runs complete · 15h19m elapsed · ~6h40m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=1200
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=1200
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=1200
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=1200
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=1200
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=1200
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=1200
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=1200
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=1200
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=1200

  553620/776400 runs complete · 15h20m elapsed · ~6h38m left

  554620/776400 runs complete · 15h22m elapsed · ~6h36m left

  555620/776400 runs complete · 15h23m elapsed · ~6h34m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=1500
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=1500
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=1500
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=1500
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=1500
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=1500
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=1500
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=1500
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=1500
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=1500

  556620/776400 runs complete · 15h24m elapsed · ~6h32m left

  557620/776400 runs complete · 15h25m elapsed · ~6h30m left

  558620/776400 runs complete · 15h27m elapsed · ~6h28m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=1800
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=1800
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=1800
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=1800
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=1800
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=1800
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=1800
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=1800
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=1800
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=1800

  559620/776400 runs complete · 15h28m elapsed · ~6h26m left

  560620/776400 runs complete · 15h30m elapsed · ~6h24m left

  561620/776400 runs complete · 15h31m elapsed · ~6h22m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=2100
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=2100
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=2100
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=2100
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=2100
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=2100
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=2100
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=2100
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=2100
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=2100

  562620/776400 runs complete · 15h32m elapsed · ~6h20m left

  563620/776400 runs complete · 15h34m elapsed · ~6h18m left

  564620/776400 runs complete · 15h35m elapsed · ~6h16m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=2400
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=2400
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=2400
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=2400
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=2400
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=2400
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=2400
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=2400
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=2400
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=2400

  565620/776400 runs complete · 15h37m elapsed · ~6h14m left

  566620/776400 runs complete · 15h38m elapsed · ~6h12m left

  567620/776400 runs complete · 15h39m elapsed · ~6h10m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=2700
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=2700
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=2700
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=2700
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=2700
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=2700
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=2700
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=2700
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=2700
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=2700

  568620/776400 runs complete · 15h40m elapsed · ~6h08m left

  569620/776400 runs complete · 15h41m elapsed · ~6h06m left

  570620/776400 runs complete · 15h43m elapsed · ~6h04m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=3000
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=3000
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=3000
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=3000
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=3000
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=3000
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=3000
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=3000
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=3000
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=3000

  571620/776400 runs complete · 15h44m elapsed · ~6h02m left

  572620/776400 runs complete · 15h45m elapsed · ~6h00m left

  573620/776400 runs complete · 15h47m elapsed · ~5h59m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=3300
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=3300
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=3300
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=3300
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=3300
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=3300
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=3300
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=3300
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=3300
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=3300

  574620/776400 runs complete · 15h48m elapsed · ~5h57m left

  575620/776400 runs complete · 15h50m elapsed · ~5h55m left

  576620/776400 runs complete · 15h51m elapsed · ~5h53m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=3600
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=3600
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=3600
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=3600
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=3600
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=3600
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=3600
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=3600
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=3600

  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=3600

  577620/776400 runs complete · 15h52m elapsed · ~5h51m left

  578620/776400 runs complete · 15h54m elapsed · ~5h49m left

  579620/776400 runs complete · 15h55m elapsed · ~5h47m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=3900
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=3900
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=3900
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=3900
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=3900
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=3900
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=3900
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=3900

  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=3900
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=3900

  580620/776400 runs complete · 15h57m elapsed · ~5h45m left

  581620/776400 runs complete · 15h58m elapsed · ~5h43m left

  582620/776400 runs complete · 15h59m elapsed · ~5h41m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=4200
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=4200
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=4200
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=4200
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=4200
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=4200
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=4200
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=4200
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=4200

  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=4200

  583620/776400 runs complete · 16h00m elapsed · ~5h39m left

  584620/776400 runs complete · 16h02m elapsed · ~5h37m left

  585620/776400 runs complete · 16h03m elapsed · ~5h36m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=4500
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=4500
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=4500
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=4500
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=4500
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=4500
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=4500
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=4500
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=4500

  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=4500

  586620/776400 runs complete · 16h05m elapsed · ~5h34m left

  587620/776400 runs complete · 16h06m elapsed · ~5h32m left

  588620/776400 runs complete · 16h07m elapsed · ~5h30m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=4800
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=4800
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=4800
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=4800
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=4800
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=4800
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=4800
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=4800

  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=4800
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=4800

  589620/776400 runs complete · 16h09m elapsed · ~5h28m left

  590620/776400 runs complete · 16h10m elapsed · ~5h26m left

  591620/776400 runs complete · 16h11m elapsed · ~5h24m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=5100
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=5100
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=5100
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=5100
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=5100
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=5100
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=5100
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=5100

  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=5100
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=5100

  592620/776400 runs complete · 16h12m elapsed · ~5h22m left

  593620/776400 runs complete · 16h14m elapsed · ~5h20m left

  594620/776400 runs complete · 16h16m elapsed · ~5h19m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=5400
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=5400
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=5400
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=5400
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=5400
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=5400
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=5400
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=5400

  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=5400
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=5400

  595620/776400 runs complete · 16h17m elapsed · ~5h17m left

  596620/776400 runs complete · 16h18m elapsed · ~5h15m left

  597620/776400 runs complete · 16h20m elapsed · ~5h13m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=5700
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=5700
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=5700
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=5700
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=5700
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=5700
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=5700

  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=5700
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=5700
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=5700

  598620/776400 runs complete · 16h21m elapsed · ~5h11m left

  599620/776400 runs complete · 16h23m elapsed · ~5h09m left

  600620/776400 runs complete · 16h24m elapsed · ~5h07m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=6000
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=6000
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=6000
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=6000
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=6000
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=6000
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=6000
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=6000

  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=6000
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=6000

  601620/776400 runs complete · 16h25m elapsed · ~5h05m left

  602620/776400 runs complete · 16h26m elapsed · ~5h04m left

  603620/776400 runs complete · 16h28m elapsed · ~5h02m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=6300
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=6300
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=6300
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=6300
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=6300
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=6300
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=6300
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=6300

  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=6300
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=6300

  604620/776400 runs complete · 16h29m elapsed · ~5h00m left

  605620/776400 runs complete · 16h30m elapsed · ~4h58m left

  606620/776400 runs complete · 16h31m elapsed · ~4h56m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=6600
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=6600
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=6600
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=6600
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=6600
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=6600
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=6600
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=6600

  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=6600
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=6600

  607620/776400 runs complete · 16h32m elapsed · ~4h54m left

  608620/776400 runs complete · 16h34m elapsed · ~4h52m left

  609620/776400 runs complete · 16h35m elapsed · ~4h50m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=6900
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=6900
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=6900
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=6900
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=6900
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=6900
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=6900
  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=6900

  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=6900
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=6900

  610620/776400 runs complete · 16h36m elapsed · ~4h48m left

  611620/776400 runs complete · 16h38m elapsed · ~4h47m left

  612620/776400 runs complete · 16h39m elapsed · ~4h45m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=7200
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=7200
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=7200
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=7200
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=7200
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=7200
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=7200

  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=7200
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=7200
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=7200

  613620/776400 runs complete · 16h40m elapsed · ~4h43m left

  614620/776400 runs complete · 16h42m elapsed · ~4h41m left

  615620/776400 runs complete · 16h43m elapsed · ~4h39m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=300  total=7500
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=300  total=7500
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=300  total=7500
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=300  total=7500
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=300  total=7500
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=300  total=7500
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=300  total=7500

  Saved: raw/rnn/Q_zz_pauli.parquet   new=300  total=7500
  Saved: raw/gru/Q_zz_pauli.parquet   new=300  total=7500
  Saved: raw/lstm/Q_zz_pauli.parquet   new=300  total=7500

  616620/776400 runs complete · 16h44m elapsed · ~4h37m left

  617620/776400 runs complete · 16h45m elapsed · ~4h35m left

  Saved: raw/decision_tree/Q_zz_pauli.parquet   new=224  total=7724
  Saved: raw/adaboost/Q_zz_pauli.parquet   new=224  total=7724
  Saved: raw/random_forest/Q_zz_pauli.parquet   new=224  total=7724
  Saved: raw/xgboost/Q_zz_pauli.parquet   new=224  total=7724
  Saved: raw/linear_svm/Q_zz_pauli.parquet   new=224  total=7724
  Saved: raw/sig_kernel/Q_zz_pauli.parquet   new=224  total=7724
  Saved: raw/linear_readout/Q_zz_pauli.parquet   new=224  total=7724

  Saved: raw/rnn/Q_zz_pauli.parquet   new=224  total=7724
  Saved: raw/gru/Q_zz_pauli.parquet   new=224  total=7724
  Saved: raw/lstm/Q_zz_pauli.parquet   new=224  total=7724

  618620/776400 runs complete · 16h46m elapsed · ~4h33m left

  619620/776400 runs complete · 16h47m elapsed · ~4h31m left

  620620/776400 runs complete · 16h48m elapsed · ~4h30m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=300
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=300
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=300
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=300
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=300
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=300
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=300
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=300
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=300
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=300

  621620/776400 runs complete · 16h49m elapsed · ~4h28m left

  622620/776400 runs complete · 16h50m elapsed · ~4h26m left

  623620/776400 runs complete · 16h52m elapsed · ~4h24m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=600
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=600
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=600
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=600
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=600
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=600
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=600
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=600
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=600
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=600

  624620/776400 runs complete · 16h53m elapsed · ~4h22m left

  625620/776400 runs complete · 16h54m elapsed · ~4h20m left

  626620/776400 runs complete · 16h56m elapsed · ~4h18m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=900
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=900
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=900
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=900
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=900
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=900
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=900
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=900
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=900
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=900

  627620/776400 runs complete · 16h57m elapsed · ~4h16m left

  628620/776400 runs complete · 16h58m elapsed · ~4h15m left

  629620/776400 runs complete · 16h59m elapsed · ~4h13m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=1200
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=1200
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=1200
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=1200
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=1200
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=1200
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=1200
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=1200
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=1200
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=1200

  630620/776400 runs complete · 17h00m elapsed · ~4h11m left

  631620/776400 runs complete · 17h01m elapsed · ~4h09m left

  632620/776400 runs complete · 17h03m elapsed · ~4h07m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=1500
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=1500
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=1500
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=1500
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=1500
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=1500
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=1500
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=1500
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=1500
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=1500

  633620/776400 runs complete · 17h04m elapsed · ~4h05m left

  634620/776400 runs complete · 17h05m elapsed · ~4h03m left

  635620/776400 runs complete · 17h06m elapsed · ~4h02m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=1800
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=1800
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=1800
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=1800
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=1800
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=1800
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=1800
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=1800
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=1800
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=1800

  636620/776400 runs complete · 17h07m elapsed · ~4h00m left

  637620/776400 runs complete · 17h08m elapsed · ~3h58m left

  638620/776400 runs complete · 17h09m elapsed · ~3h56m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=2100
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=2100
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=2100
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=2100
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=2100
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=2100
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=2100
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=2100
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=2100
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=2100

  639620/776400 runs complete · 17h10m elapsed · ~3h54m left

  640620/776400 runs complete · 17h11m elapsed · ~3h52m left

  641620/776400 runs complete · 17h13m elapsed · ~3h50m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=2400
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=2400
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=2400
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=2400
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=2400
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=2400
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=2400
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=2400
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=2400
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=2400

  642620/776400 runs complete · 17h14m elapsed · ~3h49m left

  643620/776400 runs complete · 17h15m elapsed · ~3h47m left

  644620/776400 runs complete · 17h16m elapsed · ~3h45m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=2700
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=2700
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=2700
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=2700
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=2700
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=2700
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=2700
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=2700
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=2700
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=2700

  645620/776400 runs complete · 17h17m elapsed · ~3h43m left

  646620/776400 runs complete · 17h18m elapsed · ~3h41m left

  647620/776400 runs complete · 17h19m elapsed · ~3h39m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=3000
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=3000
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=3000
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=3000
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=3000
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=3000
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=3000
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=3000
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=3000

  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=3000

  648620/776400 runs complete · 17h20m elapsed · ~3h38m left

  649620/776400 runs complete · 17h22m elapsed · ~3h36m left

  650620/776400 runs complete · 17h23m elapsed · ~3h34m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=3300
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=3300
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=3300
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=3300
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=3300
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=3300
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=3300
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=3300
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=3300
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=3300

  651620/776400 runs complete · 17h24m elapsed · ~3h32m left

  652620/776400 runs complete · 17h26m elapsed · ~3h30m left

  653620/776400 runs complete · 17h27m elapsed · ~3h29m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=3600
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=3600
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=3600
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=3600
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=3600
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=3600
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=3600
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=3600
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=3600

  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=3600

  654620/776400 runs complete · 17h28m elapsed · ~3h27m left

  655620/776400 runs complete · 17h29m elapsed · ~3h25m left

  656620/776400 runs complete · 17h30m elapsed · ~3h23m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=3900
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=3900
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=3900
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=3900
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=3900
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=3900
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=3900
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=3900
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=3900

  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=3900

  657620/776400 runs complete · 17h31m elapsed · ~3h21m left

  658620/776400 runs complete · 17h32m elapsed · ~3h20m left

  659620/776400 runs complete · 17h33m elapsed · ~3h18m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=4200
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=4200
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=4200
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=4200
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=4200
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=4200
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=4200
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=4200
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=4200

  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=4200

  660620/776400 runs complete · 17h34m elapsed · ~3h16m left

  661620/776400 runs complete · 17h35m elapsed · ~3h14m left

  662620/776400 runs complete · 17h37m elapsed · ~3h12m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=4500
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=4500
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=4500
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=4500
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=4500
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=4500
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=4500
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=4500

  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=4500
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=4500

  663620/776400 runs complete · 17h38m elapsed · ~3h10m left

  664620/776400 runs complete · 17h39m elapsed · ~3h09m left

  665620/776400 runs complete · 17h40m elapsed · ~3h07m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=4800
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=4800
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=4800
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=4800
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=4800
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=4800
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=4800
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=4800

  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=4800
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=4800

  666620/776400 runs complete · 17h41m elapsed · ~3h05m left

  667620/776400 runs complete · 17h42m elapsed · ~3h03m left

  668620/776400 runs complete · 17h44m elapsed · ~3h02m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=5100
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=5100
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=5100
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=5100
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=5100
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=5100
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=5100
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=5100
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=5100

  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=5100

  669620/776400 runs complete · 17h45m elapsed · ~3h00m left

  670620/776400 runs complete · 17h46m elapsed · ~2h58m left

  671620/776400 runs complete · 17h48m elapsed · ~2h56m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=5400
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=5400
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=5400
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=5400
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=5400
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=5400
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=5400
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=5400

  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=5400
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=5400

  672620/776400 runs complete · 17h49m elapsed · ~2h55m left

  673620/776400 runs complete · 17h50m elapsed · ~2h53m left

  674620/776400 runs complete · 17h51m elapsed · ~2h51m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=5700
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=5700
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=5700
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=5700
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=5700
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=5700
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=5700
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=5700

  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=5700
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=5700

  675620/776400 runs complete · 17h52m elapsed · ~2h49m left

  676620/776400 runs complete · 17h54m elapsed · ~2h47m left

  677620/776400 runs complete · 17h55m elapsed · ~2h46m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=6000
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=6000
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=6000
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=6000
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=6000
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=6000
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=6000
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=6000

  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=6000
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=6000

  678620/776400 runs complete · 17h56m elapsed · ~2h44m left

  679620/776400 runs complete · 17h57m elapsed · ~2h42m left

  680620/776400 runs complete · 17h59m elapsed · ~2h40m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=6300
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=6300
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=6300
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=6300
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=6300
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=6300
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=6300

  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=6300
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=6300
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=6300

  681620/776400 runs complete · 18h00m elapsed · ~2h39m left

  682620/776400 runs complete · 18h01m elapsed · ~2h37m left

  683620/776400 runs complete · 18h02m elapsed · ~2h35m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=6600
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=6600
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=6600
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=6600
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=6600
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=6600
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=6600

  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=6600
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=6600
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=6600

  684620/776400 runs complete · 18h03m elapsed · ~2h33m left

  685620/776400 runs complete · 18h04m elapsed · ~2h32m left

  686620/776400 runs complete · 18h06m elapsed · ~2h30m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=6900
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=6900
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=6900
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=6900
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=6900
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=6900
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=6900
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=6900

  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=6900
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=6900

  687620/776400 runs complete · 18h07m elapsed · ~2h28m left

  688620/776400 runs complete · 18h08m elapsed · ~2h27m left

  689620/776400 runs complete · 18h09m elapsed · ~2h25m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=7200
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=7200
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=7200
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=7200
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=7200
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=7200
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=7200
  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=7200

  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=7200
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=7200

  690620/776400 runs complete · 18h10m elapsed · ~2h23m left

  691620/776400 runs complete · 18h11m elapsed · ~2h21m left

  692620/776400 runs complete · 18h12m elapsed · ~2h20m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=300  total=7500
  Saved: raw/adaboost/Q_zz_pce.parquet   new=300  total=7500
  Saved: raw/random_forest/Q_zz_pce.parquet   new=300  total=7500
  Saved: raw/xgboost/Q_zz_pce.parquet   new=300  total=7500
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=300  total=7500
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=300  total=7500
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=300  total=7500

  Saved: raw/rnn/Q_zz_pce.parquet   new=300  total=7500
  Saved: raw/gru/Q_zz_pce.parquet   new=300  total=7500
  Saved: raw/lstm/Q_zz_pce.parquet   new=300  total=7500

  693620/776400 runs complete · 18h14m elapsed · ~2h18m left

  694620/776400 runs complete · 18h15m elapsed · ~2h16m left

  Saved: raw/decision_tree/Q_zz_pce.parquet   new=224  total=7724
  Saved: raw/adaboost/Q_zz_pce.parquet   new=224  total=7724
  Saved: raw/random_forest/Q_zz_pce.parquet   new=224  total=7724
  Saved: raw/xgboost/Q_zz_pce.parquet   new=224  total=7724
  Saved: raw/linear_svm/Q_zz_pce.parquet   new=224  total=7724
  Saved: raw/sig_kernel/Q_zz_pce.parquet   new=224  total=7724
  Saved: raw/linear_readout/Q_zz_pce.parquet   new=224  total=7724

  Saved: raw/rnn/Q_zz_pce.parquet   new=224  total=7724
  Saved: raw/gru/Q_zz_pce.parquet   new=224  total=7724
  Saved: raw/lstm/Q_zz_pce.parquet   new=224  total=7724

  695620/776400 runs complete · 18h16m elapsed · ~2h14m left

  696620/776400 runs complete · 18h17m elapsed · ~2h13m left

  697620/776400 runs complete · 18h18m elapsed · ~2h11m left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=300
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=300
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=300
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=300
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=300
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=300
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=300
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=300
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=300
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=300

  698620/776400 runs complete · 18h20m elapsed · ~2h09m left

  699620/776400 runs complete · 18h21m elapsed · ~2h07m left

  700620/776400 runs complete · 18h22m elapsed · ~2h06m left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=600
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=600
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=600
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=600
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=600
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=600
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=600
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=600
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=600
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=600

  701620/776400 runs complete · 18h23m elapsed · ~2h04m left

  702620/776400 runs complete · 18h24m elapsed · ~2h02m left

  703620/776400 runs complete · 18h25m elapsed · ~2h01m left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=900
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=900
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=900
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=900
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=900
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=900
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=900
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=900
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=900
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=900

  704620/776400 runs complete · 18h27m elapsed · ~1h59m left

  705620/776400 runs complete · 18h28m elapsed · ~1h57m left

  706620/776400 runs complete · 18h29m elapsed · ~1h55m left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=1200
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=1200
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=1200
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=1200
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=1200
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=1200
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=1200
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=1200
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=1200
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=1200

  707620/776400 runs complete · 18h30m elapsed · ~1h54m left

  708620/776400 runs complete · 18h31m elapsed · ~1h52m left

  709620/776400 runs complete · 18h32m elapsed · ~1h50m left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=1500
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=1500
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=1500
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=1500
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=1500
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=1500
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=1500
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=1500
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=1500

  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=1500

  710620/776400 runs complete · 18h33m elapsed · ~1h48m left

  711620/776400 runs complete · 18h34m elapsed · ~1h47m left

  712620/776400 runs complete · 18h35m elapsed · ~1h45m left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=1800
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=1800
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=1800
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=1800
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=1800
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=1800
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=1800
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=1800
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=1800
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=1800

  713620/776400 runs complete · 18h36m elapsed · ~1h43m left

  714620/776400 runs complete · 18h37m elapsed · ~1h42m left

  715620/776400 runs complete · 18h38m elapsed · ~1h40m left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=2100
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=2100
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=2100
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=2100
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=2100
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=2100
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=2100
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=2100
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=2100
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=2100

  716620/776400 runs complete · 18h39m elapsed · ~1h38m left

  717620/776400 runs complete · 18h40m elapsed · ~1h37m left

  718620/776400 runs complete · 18h41m elapsed · ~1h35m left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=2400
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=2400
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=2400
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=2400
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=2400
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=2400
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=2400
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=2400
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=2400
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=2400

  719620/776400 runs complete · 18h42m elapsed · ~1h33m left

  720620/776400 runs complete · 18h44m elapsed · ~1h31m left

  721620/776400 runs complete · 18h44m elapsed · ~1h30m left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=2700
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=2700
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=2700
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=2700
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=2700
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=2700
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=2700
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=2700
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=2700
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=2700

  722620/776400 runs complete · 18h45m elapsed · ~1h28m left

  723620/776400 runs complete · 18h46m elapsed · ~1h26m left

  724620/776400 runs complete · 18h47m elapsed · ~1h25m left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=3000
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=3000
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=3000
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=3000
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=3000
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=3000
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=3000
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=3000
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=3000
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=3000

  725620/776400 runs complete · 18h48m elapsed · ~1h23m left

  726620/776400 runs complete · 18h49m elapsed · ~1h21m left

  727620/776400 runs complete · 18h50m elapsed · ~1h20m left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=3300
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=3300
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=3300
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=3300
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=3300
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=3300
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=3300
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=3300
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=3300

  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=3300

  728620/776400 runs complete · 18h51m elapsed · ~1h18m left

  729620/776400 runs complete · 18h52m elapsed · ~1h16m left

  730620/776400 runs complete · 18h53m elapsed · ~1h15m left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=3600
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=3600
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=3600
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=3600
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=3600
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=3600
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=3600
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=3600
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=3600

  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=3600

  731620/776400 runs complete · 18h55m elapsed · ~1h13m left

  732620/776400 runs complete · 18h56m elapsed · ~1h11m left

  733620/776400 runs complete · 18h57m elapsed · ~1h10m left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=3900
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=3900
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=3900
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=3900
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=3900
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=3900
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=3900
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=3900

  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=3900
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=3900

  734620/776400 runs complete · 18h58m elapsed · ~1h08m left

  735620/776400 runs complete · 18h59m elapsed · ~1h06m left

  736620/776400 runs complete · 19h00m elapsed · ~1h05m left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=4200
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=4200
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=4200
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=4200
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=4200
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=4200
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=4200
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=4200
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=4200

  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=4200

  737620/776400 runs complete · 19h01m elapsed · ~1h03m left

  738620/776400 runs complete · 19h02m elapsed · ~1h01m left

  739620/776400 runs complete · 19h03m elapsed · ~59m59s left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=4500
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=4500
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=4500
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=4500
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=4500
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=4500
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=4500
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=4500
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=4500

  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=4500

  740620/776400 runs complete · 19h04m elapsed · ~58m19s left

  741620/776400 runs complete · 19h05m elapsed · ~56m39s left

  742620/776400 runs complete · 19h06m elapsed · ~54m59s left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=4800
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=4800
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=4800
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=4800
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=4800
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=4800
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=4800
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=4800

  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=4800
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=4800

  743620/776400 runs complete · 19h07m elapsed · ~53m20s left

  744620/776400 runs complete · 19h08m elapsed · ~51m41s left

  745620/776400 runs complete · 19h09m elapsed · ~50m01s left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=5100
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=5100
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=5100
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=5100
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=5100
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=5100
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=5100
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=5100

  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=5100
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=5100

  746620/776400 runs complete · 19h10m elapsed · ~48m22s left

  747620/776400 runs complete · 19h11m elapsed · ~46m44s left

  748620/776400 runs complete · 19h12m elapsed · ~45m04s left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=5400
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=5400
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=5400
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=5400
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=5400
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=5400
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=5400

  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=5400
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=5400
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=5400

  749620/776400 runs complete · 19h12m elapsed · ~43m26s left

  750620/776400 runs complete · 19h13m elapsed · ~41m47s left

  751620/776400 runs complete · 19h14m elapsed · ~40m08s left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=5700
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=5700
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=5700
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=5700
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=5700
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=5700
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=5700
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=5700

  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=5700
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=5700

  752620/776400 runs complete · 19h16m elapsed · ~38m30s left

  753620/776400 runs complete · 19h17m elapsed · ~36m52s left

  754620/776400 runs complete · 19h18m elapsed · ~35m14s left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=6000
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=6000
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=6000
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=6000
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=6000
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=6000
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=6000
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=6000

  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=6000
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=6000

  755620/776400 runs complete · 19h19m elapsed · ~33m36s left

  756620/776400 runs complete · 19h20m elapsed · ~31m58s left

  757620/776400 runs complete · 19h21m elapsed · ~30m21s left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=6300
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=6300
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=6300
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=6300
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=6300
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=6300
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=6300
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=6300

  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=6300
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=6300

  758620/776400 runs complete · 19h22m elapsed · ~28m43s left

  759620/776400 runs complete · 19h23m elapsed · ~27m05s left

  760620/776400 runs complete · 19h24m elapsed · ~25m27s left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=6600
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=6600
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=6600
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=6600
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=6600
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=6600
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=6600

  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=6600
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=6600
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=6600

  761620/776400 runs complete · 19h25m elapsed · ~23m50s left

  762620/776400 runs complete · 19h26m elapsed · ~22m12s left

  763620/776400 runs complete · 19h28m elapsed · ~20m36s left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=6900
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=6900
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=6900
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=6900

  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=6900
  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=6900
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=6900
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=6900
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=6900

  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=6900

  764620/776400 runs complete · 19h30m elapsed · ~19m00s left

  765620/776400 runs complete · 19h33m elapsed · ~17m24s left

  766620/776400 runs complete · 19h36m elapsed · ~15m48s left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=7200
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=7200
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=7200
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=7200
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=7200

  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=7200
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=7200
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=7200
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=7200
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=7200

  767620/776400 runs complete · 19h39m elapsed · ~14m12s left

  768620/776400 runs complete · 19h42m elapsed · ~12m36s left

  769620/776400 runs complete · 19h45m elapsed · ~11m00s left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=300  total=7500
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=300  total=7500
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=300  total=7500
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=300  total=7500
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=300  total=7500

  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=300  total=7500
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=300  total=7500
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=300  total=7500
  Saved: raw/gru/Q_zz_single_bit.parquet   new=300  total=7500
  Saved: raw/lstm/Q_zz_single_bit.parquet   new=300  total=7500

  770620/776400 runs complete · 19h47m elapsed · ~9m23s left

  771620/776400 runs complete · 19h50m elapsed · ~7m46s left

  Saved: raw/decision_tree/Q_zz_single_bit.parquet   new=224  total=7724
  Saved: raw/adaboost/Q_zz_single_bit.parquet   new=224  total=7724
  Saved: raw/random_forest/Q_zz_single_bit.parquet   new=224  total=7724
  Saved: raw/xgboost/Q_zz_single_bit.parquet   new=224  total=7724
  Saved: raw/linear_svm/Q_zz_single_bit.parquet   new=224  total=7724

  Saved: raw/sig_kernel/Q_zz_single_bit.parquet   new=224  total=7724
  Saved: raw/linear_readout/Q_zz_single_bit.parquet   new=224  total=7724
  Saved: raw/rnn/Q_zz_single_bit.parquet   new=224  total=7724
  Saved: raw/gru/Q_zz_single_bit.parquet   new=224  total=7724

  Saved: raw/lstm/Q_zz_single_bit.parquet   new=224  total=7724
Loop complete. Total rows: 733780 in 19h51m

Runs with errors: 0

## 5. Summarize

Saving merges rather than overwrites: only the rows a run recomputed are replaced, so teammates running other models or tracks are unaffected.

In [7]:
# summaries cover everything on disk for the active models/tracks, not just this run
all_results = load_results(RESULTS_DIR, models=ACTIVE_MODELS, tracks=ACTIVE_TRACKS)
summary = summarize(all_results)
summary

                                                   mse       mae  median_ae  \
model    track              target   horizon
adaboost Q_heisenberg_pauli CPIAUCSL 1        0.000009  0.002195   0.002195
                                     3        0.000057  0.005282   0.005282
                                     6        0.000177  0.009400   0.009400
                            INDPRO   1        0.000096  0.005598   0.005598
                                     3        0.000387  0.011618   0.011618
...                                                ...       ...        ...
xgboost  Q_zz_single_bit    PAYEMS   3        0.000133  0.005300   0.005300
                                     6        0.000249  0.009272   0.009272
                            S&P 500  1        0.001528  0.028999   0.028999
                                     3        0.005787  0.057070   0.057070
                                     6        0.012958  0.085673   0.085673

                                                  rmse      mase     rmspe
model    track              target   horizon
adaboost Q_heisenberg_pauli CPIAUCSL 1        0.002195  1.161184  1.746241
                                     3        0.005282  1.141444  2.411655
                                     6        0.009400  1.342237  1.400389
                            INDPRO   1        0.005598  0.892536  6.417678
                                     3        0.011618  0.996155  4.675681
...                                                ...       ...       ...
xgboost  Q_zz_single_bit    PAYEMS   3        0.005300  1.932013  2.444054
                                     6        0.009272  1.731275  5.349831
                            S&P 500  1        0.028999  0.877603  3.797841
                                     3        0.057070  0.823439  2.105983
                                     6        0.085673  0.855550  1.908518

[1200 rows x 6 columns]

In [8]:
# recession (1) vs expansion (0)
summary_disagg = disaggregate_by_usrec(load_results(RESULTS_DIR), usrec)  # all models/tracks on disk
write_csv(summary_disagg, RESULTS_DIR / "summary_disaggregated.csv")
summary_disagg

                                                     mse       mae  median_ae  \
model   track           target   horizon usrec
AR6     B               CPIAUCSL 1       0      0.000005  0.001586   0.001586
                                         1      0.000019  0.003242   0.003242
                                 3       0      0.000027  0.003785   0.003785
                                         1      0.000161  0.009629   0.009629
                                 6       0      0.000093  0.006961   0.006961
...                                                  ...       ...        ...
xgboost Q_zz_single_bit S&P 500  1       1      0.003793  0.046751   0.046751
                                 3       0      0.004647  0.051856   0.051856
                                         1      0.014571  0.097236   0.097236
                                 6       0      0.009090  0.074541   0.074541
                                         1      0.042596  0.170972   0.170972

                                                    rmse      mase     rmspe
model   track           target   horizon usrec
AR6     B               CPIAUCSL 1       0      0.001586  0.860288  1.348996
                                         1      0.003242  1.546022  1.333686
                                 3       0      0.003785  0.823602  2.077020
                                         1      0.009629  1.925051  1.826281
                                 6       0      0.006961  1.001412  1.211426
...                                                  ...       ...       ...
xgboost Q_zz_single_bit S&P 500  1       1      0.046751  1.326651  1.306572
                                 3       0      0.051856  0.752689  2.227379
                                         1      0.097236  1.368405  1.170910
                                 6       0      0.074541  0.752026  2.015619
                                         1      0.170972  1.648774  1.090794

[2976 rows x 6 columns]

In [9]:
# one row per (run, test date): y_true vs y_pred
predictions = explode_predictions(all_results)
runtime = all_results.groupby(["model", "track"])["runtime_sec"].agg(["mean", "sum"]).round(3)
display(predictions.head(), runtime)

,model,track,target,horizon,fold_id,date,y_true,y_pred
0,adaboost,Q_heisenberg_pauli,CPIAUCSL,1,0,1972-04-01,0.002407,0.002688
1,adaboost,Q_heisenberg_pauli,CPIAUCSL,1,1,1972-05-01,0.002401,0.003331
2,adaboost,Q_heisenberg_pauli,CPIAUCSL,1,2,1972-06-01,0.002395,0.002874
3,adaboost,Q_heisenberg_pauli,CPIAUCSL,1,3,1972-07-01,0.002389,0.002904
4,adaboost,Q_heisenberg_pauli,CPIAUCSL,1,4,1972-08-01,0.004762,0.002870

                                   mean      sum
model    track
adaboost Q_heisenberg_pauli       0.062  475.064
         Q_heisenberg_pce         0.042  323.327
         Q_heisenberg_single_bit  0.044  342.873
         Q_su_bitstring           0.082  632.016
         Q_su_pauli               0.096  745.030
...                                 ...      ...
xgboost  Q_su_pce                 0.029  220.882
         Q_su_single_bit          0.012   91.242
         Q_zz_pauli               0.024  184.144
         Q_zz_pce                 0.013  102.046
         Q_zz_single_bit          0.014  111.337

[100 rows x 2 columns]